In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
pip install pandas numpy matplotlib seaborn scikit-learn networkx pyarrow jupyter ipykernel tqdm

Requirement already satisfied: pandas in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (3.0.3)
Requirement already satisfied: numpy in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (2.5.1)
Requirement already satisfied: matplotlib in c:\Users\koush\miniforge3\Lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in c:\Users\koush\miniforge3\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\Users\koush\miniforge3\Lib\site-packages (1.9.0)
Requirement already satisfied: networkx in c:\Users\koush\miniforge3\Lib\site-packages (3.6.1)
Requirement already satisfied: pyarrow in c:\Users\koush\miniforge3\Lib\site-packages (25.0.0)
Requirement already satisfied: jupyter in c:\Users\koush\miniforge3\Lib\site-packages (1.1.1)
Requirement already satisfied: ipykernel in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (6.29.5)
Requirement already satisfied: tqdm in c:\Users\koush\miniforge3\Lib\site-packages (4.66.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\koush\miniforge3\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\koush\miniforge3\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\koush\miniforge3\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=9 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\koush\miniforge3\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\koush\miniforge3\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\koush\miniforge3\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\koush\miniforge3\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\koush\miniforge3\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: notebook in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter) (7.6.1)
Requirement already satisfied: jupyter-console in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter) (7.17.1)
Requirement already satisfied: ipywidgets in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from jupyter) (8.1.8)
Requirement already satisfied: jupyterlab in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter) (4.6.2)
Requirement already satisfied: comm>=0.1.1 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (1.8.12)
Requirement already satisfied: ipython>=7.23.1 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (8.31.0)
Requirement already satisfied: jupyter-client>=6.1.12 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (0.1.7)
Requirement already satisfied: nest-asyncio in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: psutil in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (6.1.1)
Requirement already satisfied: pyzmq>=24 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (26.2.0)
Requirement already satisfied: tornado>=6.1 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (6.4.2)
Requirement already satisfied: traitlets>=5.4.0 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama in c:\Users\koush\miniforge3\Lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: decorator in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)
Requirement already satisfied: jedi>=0.16 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel) (3.0.48)
Requirement already satisfied: pygments>=2.4.0 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel) (2.19.1)
Requirement already satisfied: stack_data in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.4)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.3.6)
Requirement already satisfied: pywin32>=300 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (308)
Requirement already satisfied: six>=1.5 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipywidgets->jupyter) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from ipywidgets->jupyter) (3.0.16)
Requirement already satisfied: async-lru>=1.0.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-builder>=1.0.2 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab->jupyter) (1.2.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab->jupyter) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab->jupyter) (2.20.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: anyio in c:\Users\koush\miniforge3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.14.2)
Requirement already satisfied: certifi in c:\Users\koush\miniforge3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\Users\koush\miniforge3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in c:\Users\koush\miniforge3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.8)
Requirement already satisfied: h11>=0.16 in c:\Users\koush\miniforge3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.26.0)
Requirement already satisfied: pywinpty!=3.0.4,>=2.0.1 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0.5)
Requirement already satisfied: send2trash>=1.8.2 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.9.0)
Requirement already satisfied: babel>=2.10 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: requests>=2.31 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.32.3)
Requirement already satisfied: typing_extensions>=4.5 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter) (4.13.0)
Requirement already satisfied: argon2-cffi-bindings in c:\Users\koush\miniforge3\Lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2026.6.3)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\Users\koush\miniforge3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\Users\koush\miniforge3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in c:\Users\koush\miniforge3\Lib\site-packages (from nbconvert->jupyter) (4.15.0)
Requirement already satisfied: bleach!=5.0.0 in c:\Users\koush\miniforge3\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.4.0)
Requirement already satisfied: defusedxml in c:\Users\koush\miniforge3\Lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\Users\koush\miniforge3\Lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\Users\koush\miniforge3\Lib\site-packages (from nbconvert->jupyter) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\Users\koush\miniforge3\Lib\site-packages (from nbconvert->jupyter) (0.11.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\Users\koush\miniforge3\Lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\Users\koush\miniforge3\Lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2>=1.1.0 in c:\Users\koush\miniforge3\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\Users\koush\miniforge3\Lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.22.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\koush\miniforge3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\koush\miniforge3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.2.2)
Requirement already satisfied: lark>=1.2.2 in c:\Users\koush\miniforge3\Lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in c:\Users\koush\miniforge3\Lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.17.0)
Requirement already satisfied: pycparser in c:\Users\koush\miniforge3\Lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.22)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\koush\miniforge3\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.9.1)
Requirement already satisfied: arrow>=0.15.0 in c:\Users\koush\miniforge3\Lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.4.0)
Requirement already satisfied: executing>=1.2.0 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (3.0.0)
Requirement already satisfied: pure-eval in C:\Users\koush\AppData\Roaming\Python\Python312\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~andas (C:\Users\koush\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\koush\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\koush\AppData\Roaming\Python\Python312\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
from pathlib import Path

DATA_DIR = Path(r"C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++")

for file in DATA_DIR.rglob("*.csv"):
    print(file.name, "->", file)

AddrTx_edgelist.csv -> C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\AddrTx_edgelist.csv
TxAddr_edgelist.csv -> C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\TxAddr_edgelist.csv
txs_classes.csv -> C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\txs_classes.csv
txs_edgelist.csv -> C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\txs_edgelist.csv
txs_features.csv -> C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\txs_features.csv
wallets_classes.csv -> C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\wallets_classes.csv
wallets_features.csv -> C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\wallets_features.csv
wallets_features_classes_combined.csv -> C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\wallets_features_classes_combined.csv

In [4]:
import pandas as pd

files = {
    "txs_features": DATA_DIR / "txs_features.csv",
    "txs_classes": DATA_DIR / "txs_classes.csv",
    "txs_edgelist": DATA_DIR / "txs_edgelist.csv",
    "wallets_features": DATA_DIR / "wallets_features.csv",
    "wallets_classes": DATA_DIR / "wallets_classes.csv",
    "AddrTx_edgelist": DATA_DIR / "AddrTx_edgelist.csv",
    "TxAddr_edgelist": DATA_DIR / "TxAddr_edgelist.csv",
    "wallets_combined": DATA_DIR / "wallets_features_classes_combined.csv"
}

for name, path in files.items():
    print("\n" + "="*60)
    print(name)
    print("File:", path)
    print("Size:", round(path.stat().st_size / (1024**2), 2), "MB")

    sample = pd.read_csv(path, nrows=5)

    print("Columns:", len(sample.columns))
    print("Column names:")
    print(sample.columns.tolist())
    print("\nFirst 5 rows:")
    display(sample.head())

============================================================
txs_features
File: C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\txs_features.csv
Size: 662.6 MB
Columns: 184
Column names:
['txId', 'Time step', 'Local_feature_1', 'Local_feature_2', 'Local_feature_3', 'Local_feature_4', 'Local_feature_5', 'Local_feature_6', 'Local_feature_7', 'Local_feature_8', 'Local_feature_9', 'Local_feature_10', 'Local_feature_11', 'Local_feature_12', 'Local_feature_13', 'Local_feature_14', 'Local_feature_15', 'Local_feature_16', 'Local_feature_17', 'Local_feature_18', 'Local_feature_19', 'Local_feature_20', 'Local_feature_21', 'Local_feature_22', 'Local_feature_23', 'Local_feature_24', 'Local_feature_25', 'Local_feature_26', 'Local_feature_27', 'Local_feature_28', 'Local_feature_29', 'Local_feature_30', 'Local_feature_31', 'Local_feature_32', 'Local_feature_33', 'Local_feature_34', 'Local_feature_35', 'Local_feature_36', 'Local_feature_37', 'Local_feature_38', 'Local_feature_39', 'Local_feature_40', 'Local_feature_41', 'Local_feature_42', 'Local_feature_43', 'Local_feature_44', 'Local_feature_45', 'Local_feature_46', 'Local_feature_47', 'Local_feature_48', 'Local_feature_49', 'Local_feature_50', 'Local_feature_51', 'Local_feature_52', 'Local_feature_53', 'Local_feature_54', 'Local_feature_55', 'Local_feature_56', 'Local_feature_57', 'Local_feature_58', 'Local_feature_59', 'Local_feature_60', 'Local_feature_61', 'Local_feature_62', 'Local_feature_63', 'Local_feature_64', 'Local_feature_65', 'Local_feature_66', 'Local_feature_67', 'Local_feature_68', 'Local_feature_69', 'Local_feature_70', 'Local_feature_71', 'Local_feature_72', 'Local_feature_73', 'Local_feature_74', 'Local_feature_75', 'Local_feature_76', 'Local_feature_77', 'Local_feature_78', 'Local_feature_79', 'Local_feature_80', 'Local_feature_81', 'Local_feature_82', 'Local_feature_83', 'Local_feature_84', 'Local_feature_85', 'Local_feature_86', 'Local_feature_87', 'Local_feature_88', 'Local_feature_89', 'Local_feature_90', 'Local_feature_91', 'Local_feature_92', 'Local_feature_93', 'Aggregate_feature_1', 'Aggregate_feature_2', 'Aggregate_feature_3', 'Aggregate_feature_4', 'Aggregate_feature_5', 'Aggregate_feature_6', 'Aggregate_feature_7', 'Aggregate_feature_8', 'Aggregate_feature_9', 'Aggregate_feature_10', 'Aggregate_feature_11', 'Aggregate_feature_12', 'Aggregate_feature_13', 'Aggregate_feature_14', 'Aggregate_feature_15', 'Aggregate_feature_16', 'Aggregate_feature_17', 'Aggregate_feature_18', 'Aggregate_feature_19', 'Aggregate_feature_20', 'Aggregate_feature_21', 'Aggregate_feature_22', 'Aggregate_feature_23', 'Aggregate_feature_24', 'Aggregate_feature_25', 'Aggregate_feature_26', 'Aggregate_feature_27', 'Aggregate_feature_28', 'Aggregate_feature_29', 'Aggregate_feature_30', 'Aggregate_feature_31', 'Aggregate_feature_32', 'Aggregate_feature_33', 'Aggregate_feature_34', 'Aggregate_feature_35', 'Aggregate_feature_36', 'Aggregate_feature_37', 'Aggregate_feature_38', 'Aggregate_feature_39', 'Aggregate_feature_40', 'Aggregate_feature_41', 'Aggregate_feature_42', 'Aggregate_feature_43', 'Aggregate_feature_44', 'Aggregate_feature_45', 'Aggregate_feature_46', 'Aggregate_feature_47', 'Aggregate_feature_48', 'Aggregate_feature_49', 'Aggregate_feature_50', 'Aggregate_feature_51', 'Aggregate_feature_52', 'Aggregate_feature_53', 'Aggregate_feature_54', 'Aggregate_feature_55', 'Aggregate_feature_56', 'Aggregate_feature_57', 'Aggregate_feature_58', 'Aggregate_feature_59', 'Aggregate_feature_60', 'Aggregate_feature_61', 'Aggregate_feature_62', 'Aggregate_feature_63', 'Aggregate_feature_64', 'Aggregate_feature_65', 'Aggregate_feature_66', 'Aggregate_feature_67', 'Aggregate_feature_68', 'Aggregate_feature_69', 'Aggregate_feature_70', 'Aggregate_feature_71', 'Aggregate_feature_72', 'in_txs_degree', 'out_txs_degree', 'total_BTC', 'fees', 'size', 'num_input_addresses', 'num_output_addresses', 'in_BTC_min', 'in_BTC_max', 'in_BTC_mean', 'in_BTC_median', 'in_BTC_total', 'out_BTC_min', 'out_BTC_max', 'out_BTC_mean', 'out_BTC_median', 'out_BTC_total']

First 5 rows:

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,Local_feature_9,Local_feature_10,Local_feature_11,Local_feature_12,Local_feature_13,Local_feature_14,Local_feature_15,Local_feature_16,Local_feature_17,Local_feature_18,Local_feature_19,Local_feature_20,Local_feature_21,Local_feature_22,Local_feature_23,Local_feature_24,Local_feature_25,Local_feature_26,Local_feature_27,Local_feature_28,Local_feature_29,Local_feature_30,Local_feature_31,Local_feature_32,Local_feature_33,Local_feature_34,Local_feature_35,Local_feature_36,Local_feature_37,Local_feature_38,Local_feature_39,Local_feature_40,Local_feature_41,Local_feature_42,Local_feature_43,Local_feature_44,Local_feature_45,Local_feature_46,Local_feature_47,Local_feature_48,Local_feature_49,Local_feature_50,Local_feature_51,Local_feature_52,Local_feature_53,Local_feature_54,Local_feature_55,Local_feature_56,Local_feature_57,Local_feature_58,Local_feature_59,Local_feature_60,Local_feature_61,Local_feature_62,Local_feature_63,Local_feature_64,Local_feature_65,Local_feature_66,Local_feature_67,Local_feature_68,Local_feature_69,Local_feature_70,Local_feature_71,Local_feature_72,Local_feature_73,Local_feature_74,Local_feature_75,Local_feature_76,Local_feature_77,Local_feature_78,Local_feature_79,Local_feature_80,Local_feature_81,Local_feature_82,Local_feature_83,Local_feature_84,Local_feature_85,Local_feature_86,Local_feature_87,Local_feature_88,Local_feature_89,Local_feature_90,Local_feature_91,Local_feature_92,Local_feature_93,Aggregate_feature_1,Aggregate_feature_2,Aggregate_feature_3,Aggregate_feature_4,Aggregate_feature_5,Aggregate_feature_6,Aggregate_feature_7,Aggregate_feature_8,Aggregate_feature_9,Aggregate_feature_10,Aggregate_feature_11,Aggregate_feature_12,Aggregate_feature_13,Aggregate_feature_14,Aggregate_feature_15,Aggregate_feature_16,Aggregate_feature_17,Aggregate_feature_18,Aggregate_feature_19,Aggregate_feature_20,Aggregate_feature_21,Aggregate_feature_22,Aggregate_feature_23,Aggregate_feature_24,Aggregate_feature_25,Aggregate_feature_26,Aggregate_feature_27,Aggregate_feature_28,Aggregate_feature_29,Aggregate_feature_30,Aggregate_feature_31,Aggregate_feature_32,Aggregate_feature_33,Aggregate_feature_34,Aggregate_feature_35,Aggregate_feature_36,Aggregate_feature_37,Aggregate_feature_38,Aggregate_feature_39,Aggregate_feature_40,Aggregate_feature_41,Aggregate_feature_42,Aggregate_feature_43,Aggregate_feature_44,Aggregate_feature_45,Aggregate_feature_46,Aggregate_feature_47,Aggregate_feature_48,Aggregate_feature_49,Aggregate_feature_50,Aggregate_feature_51,Aggregate_feature_52,Aggregate_feature_53,Aggregate_feature_54,Aggregate_feature_55,Aggregate_feature_56,Aggregate_feature_57,Aggregate_feature_58,Aggregate_feature_59,Aggregate_feature_60,Aggregate_feature_61,Aggregate_feature_62,Aggregate_feature_63,Aggregate_feature_64,Aggregate_feature_65,Aggregate_feature_66,Aggregate_feature_67,Aggregate_feature_68,Aggregate_feature_69,Aggregate_feature_70,Aggregate_feature_71,Aggregate_feature_72,in_txs_degree,out_txs_degree,total_BTC,fees,size,num_input_addresses,num_output_addresses,in_BTC_min,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total
0,3321,1,-0.169615,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160199,-0.166062,-0.049707,-0.162507,-0.028741,-0.035391,-0.042955,-0.013282,-0.042183,-0.168770,-0.171416,-0.172277,-1.373657,-1.371460,-0.139663,-0.148869,-0.080147,-0.155604,-0.010763,-0.012107,-0.139665,-0.148864,-0.080147,-0.155604,-0.010669,-0.012005,-0.024668,-0.031272,-0.023045,-0.026214,0.001428,0.001483,-0.226298,-0.238504,-0.075256,-0.234053,0.037468,0.043444,-0.226681,-0.242726,-0.097895,-0.235378,0.036577,0.042345,1.830780,1.378639,-0.232553,1.686410,0.048767,0.052956,-0.038877,-0.172804,-0.163071,-0.160801,-1.316342,-1.315388,-0.038872,-0.172793,-0.163060,-0.160794,-1.316333,-1.315375,-0.017032,-0.030026,-0.017640,-0.015071,2.146899,2.148396,-0.093535,-0.263634,-0.249970,-0.262749,1.133527,1.135947,-0.057425,-0.261929,-0.254785,-0.258624,1.125590,1.128038,-0.087322,0.780884,1.079939,0.722695,1.135523,1.135279,-0.168245,-0.200866,-0.116817,-0.190577,-0.014659,-0.018849,-1.457761,-1.493861,-0.083459,-1.485777,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.02606,-0.02766,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.106963,-0.179531,-0.166280,-0.187518,-1.159649,-1.160129,-1.371865,-1.352048,-0.295364,-1.401266,-0.975738,-0.975237,-0.158413,-0.451760,-0.420758,-0.430701,-1.015963,-1.016230,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.003773,-0.562664,-0.577099,-0.500080,0.241128,0.241406,-0.098889,-0.087490,-0.084674,-0.140597,1.519700,1.521399,1.0,0.0,0.533972,0.0001,225.0,1.0,2.0,0.534072,0.534072,0.534072,0.534072,0.534072,1.668990e-01,0.367074,0.266986,0.266986,0.533972
1,11108,1,-0.137586,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.127429,-0.133751,-0.049707,-0.129773,-0.028741,-0.035391,-0.042955,-0.013282,-0.003952,-0.138560,-0.139821,-0.134358,0.887058,0.884557,-0.139564,-0.148805,-0.080147,-0.155520,-0.010763,-0.012107,-0.139566,-0.148800,-0.080147,-0.155520,-0.010669,-0.012005,-0.024530,-0.031142,-0.023045,-0.026079,0.001428,0.001483,-0.226837,-0.239012,-0.075256,-0.234581,0.037468,0.043444,-0.226829,-0.242870,-0.097895,-0.235524,0.036577,0.042345,-0.288031,-0.383568,-0.232553,-0.346677,0.048767,0.052956,-0.038480,-0.172741,-0.163066,-0.160680,-1.316342,-1.315388,-0.038476,-0.172730,-0.163055,-0.160674,-1.316333,-1.315375,-0.017017,-0.029960,-0.017570,-0.015001,2.146899,2.148396,-0.092415,-0.262615,-0.249047,-0.261598,-1.471764,-1.470277,-0.054370,-0.261799,-0.254890,-0.258254,-1.499972,-1.498585,-0.057942,-0.240245,-0.168005,-0.178427,-1.084907,-1.084845,-0.147555,-0.184622,-0.116817,-0.170331,-0.014659,-0.018849,-1.457825,-1.493927,-0.083459,-1.485842,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.02606,-0.02766,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.100250,-0.185437,-0.175308,-0.192920,1.064205,1.063787,-1.373782,-1.352048,-0.290966,-1.402204,-0.975738,-0.975237,-0.168742,-0.429352,-0.389444,-0.412059,-1.015963,-1.016230,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.216814,-0.605631,-0.562153,-0.600999,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792,1.0,1.0,5.611778,0.0001,225.0,1.0,2.0,5.611878,5.611878,5.611878,5.611878,5.611878,5.861940e-01,5.025584,2.805889,2.805889,5.611778
2,51816,1,-0.170103,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160699,-0.166555,-0.049707,-0.163006,-0.028741,-0.035391,-0.042955,-0.013282,-0.036613,-0.169668,-0.172904,-0.172855,-1.373657,-1.371460,-0.139731,-0.148912,-0.080147,-0.155661,-0.010763,-0.012107,-0.139732,-0.148907,-0.080147,-0.155661,-0.010669,-0.012005,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227215,-0.239368,-0.075256,-0.234952,0.037468,0.043444,-0.227203,-0.243236,-0.097895,-0.235896,0.036577,0.042345,-0.414002,-0.488337,-0.232553,-0.467551,0.048767,0.052956,-0.039149,-0.172893,-0.163124,-0.160931,-1.316342,-1.315388,-0.039144,-0.172882,-0.163113,-0.160924,-1.316333,-1.315375,-0.017032,-0.029966,-0.017576,-0.015008,-2.428426,-2.429065,-0.095403,-0.264074,-0.250213,-0.263399,-1.471764,-1.470277,-0.059013,-0.262228,-0.254967,-0.259052,-1.499972,-1.498585,-0.293754,1.026982,1.469183,0.874614,-1.084907,-1.084845,-0.169178,-0.201598,-0.116817,-0.191490,-0.014659,-0.018849,-1.458049,-1.494155,-0.083459,-1.486069,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.02606,-0.02766,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.121111,-0.199742,-0.188714,-0.213667,-1.159649,-1.160129,-1.373902,-1.352048,-0.290691,-1.402262,-0.975738,-0.975237,-0.168742,-0.458162,-0.424672,-0.440022,0.143001,0.142525,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.216814,-0.617907,-0.577099,-0.613614,0.241128,0.241406,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792,1.0,1.0,0.456508,0.0001,226.0,1.0,2.0,0.456608,0.456608,0.456608,0.456608,0.456608,2.279902e-01,0.228518,0.228254,0.228254,0.456508
3,68869,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,-0.118555,0.300047,-0.145947,2.017758,1.189967,-0.042955,-0.013282,0.054659,-0.118754,-0.121849,-0.106751,-1.373657,-1.371460,-0.139302,-0.148638,-0.080147,-0.155297,-0.010763,-0.012107,-0.139303,-0.148633,-0.080147,-0.155297,-0.010669,-0.012005,-0.024667,-0.031270,-0.023045,-0.026213,0.001428,0.001483,-0.225929,-0.238157,-0.075256,-0.233692,0.037468,0.043444,-0.226790,-0.242832,-0.097895,-0.235485,0.036577,0.042345,1.779449,1.335947,-0.232553,1.637156,0.048767,0.052956,-0.038211,-0.172643,-0.163004,-0.160543,0.923473,0.923011,-0.038207,-0.172632,-0.162993,-0.160536,0.923516,0.923110,-0.017032,-0.030025,-0.017639,-0.015070,2.146899,2.148396,-0.094058,-0.263316,-0.249584,-0.262486,1.133527,1.135947,-0.056814,-0.262032,-0.254938,-0.258681,1.125590,1.128038,1.056058,0.745604,0.529777,1.065507,1.135523,1.135279,-0.169418,-0.173724,-0.056760,-0.179202,2.105260,1.256720,-1.624659,-1.495881,1.607475,-1.543580,-0.086866,1.339449,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.115534,-0.021730,-0.087925,-0.02606,-0.02766,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.104489,-0.173559,-0.159261,-0.180144,-1.159649,-1.160129,-1.373723,-1.352048,-0.291104,-1.402174,1.342003,1.340733,-0.168742,-0.458162,-0.424672,-0.440022,0.143001,0.142525,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.216814,-0.611769,-0.569626,-0.607306,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792,0.0,1.0,9.308800,0.0001,853.0,3.0,2.0,0.308900,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800
4,89273,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,5.252974,-0.049707,5.327423,-0.028741,-0.035391,265.263236,-0.013282,-0.057401,0.096439,-0.167593,-0.175293,-0.474922,-1.371460,1.828567,1.107041,-0.080147,1.512162,-0.010763,-0.012107,1.828864,1.107130,-0.080147,1.512340,-0.010669,-0.012005,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.210772,-0.223886,-0.075256,-0.218857,0.037468,0.043444,-0.210158,-0.226564,-0.097895,-0.218953,0.036577,0.042345,6.068082,4.902787,-0.232553,5.752276,0.048767,0.052956,-0.039151,-0.091613,-0.161502,-0.160686,-0.264758,-0.707181,-0.039146,-0.091595,-0.161492,-0.160680,-0.264359,-0.702900,-0.017032,3.203811,0.025727,-0.013853,-0.175326,0.184296,-0.095403,-0.197997,-0.246099,-0.258120,-0.652569,-0.822931,-0.059135,-0.227441,-0.251673,-0.255840,-0.756654,-0.846083,-0.293897,5.105231,0.736121,1.871421,-0.090956,-0.100024,10.440725,8.127848,-0.116817,10.190558,-0.014659,-0.018849,-1.458081,-1.494187,-0.083459,-1.486102,-0.088798,-0.090437,-0.177664,-0.224985,-0.134546,-0.205434,-0.003175,-0.004094,-1.626385,-1.781034,-0.349933,-1.772827,-0.004358,-0.004194,2.809553,1.533707,-0.137323,2.558191,-0.02606,-0.02766,-0.064170,-0.126676,-0.097719,-0.103061,0.003143,0.002426,-0.124895,5.678743,0.801359,0.091790,-0.050514,-0.370849,-1.373902,3.443178,2.517666,-1.043190,0.471949,0.605886,-0.179070,2.739765,-0.021386,-0.245374,0.064599,0.030362,-1.511910,1.192421,1.085161,-0.222904,0.094796,0.084615,-0.216814,4.010246,1.258630,0.982479,0.118347,0.091066,-0.098889,0.854508,-0.066727,-0.150067,-0.080760,-0.070977,1.0,288.0,852.164680,0.0000,445268.0,1.0,13107.0,852.164680,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680

============================================================
txs_classes
File: C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\txs_classes.csv
Size: 2.25 MB
Columns: 2
Column names:
['txId', 'class']

First 5 rows:

    txId  class
0   3321      3
1  11108      3
2  51816      3
3  68869      2
4  89273      2

============================================================
txs_edgelist
File: C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\txs_edgelist.csv
Size: 4.26 MB
Columns: 2
Column names:
['txId1', 'txId2']

First 5 rows:

       txId1      txId2
0  230425980    5530458
1  232022460  232438397
2  230460314  230459870
3  230333930  230595899
4  232013274  232029206

============================================================
wallets_features
File: C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\wallets_features.csv
Size: 578.37 MB
Columns: 57
Column names:
['address', 'Time step', 'num_txs_as_sender', 'num_txs_as receiver', 'first_block_appeared_in', 'last_block_appeared_in', 'lifetime_in_blocks', 'total_txs', 'first_sent_block', 'first_received_block', 'num_timesteps_appeared_in', 'btc_transacted_total', 'btc_transacted_min', 'btc_transacted_max', 'btc_transacted_mean', 'btc_transacted_median', 'btc_sent_total', 'btc_sent_min', 'btc_sent_max', 'btc_sent_mean', 'btc_sent_median', 'btc_received_total', 'btc_received_min', 'btc_received_max', 'btc_received_mean', 'btc_received_median', 'fees_total', 'fees_min', 'fees_max', 'fees_mean', 'fees_median', 'fees_as_share_total', 'fees_as_share_min', 'fees_as_share_max', 'fees_as_share_mean', 'fees_as_share_median', 'blocks_btwn_txs_total', 'blocks_btwn_txs_min', 'blocks_btwn_txs_max', 'blocks_btwn_txs_mean', 'blocks_btwn_txs_median', 'blocks_btwn_input_txs_total', 'blocks_btwn_input_txs_min', 'blocks_btwn_input_txs_max', 'blocks_btwn_input_txs_mean', 'blocks_btwn_input_txs_median', 'blocks_btwn_output_txs_total', 'blocks_btwn_output_txs_min', 'blocks_btwn_output_txs_max', 'blocks_btwn_output_txs_mean', 'blocks_btwn_output_txs_median', 'num_addr_transacted_multiple', 'transacted_w_address_total', 'transacted_w_address_min', 'transacted_w_address_max', 'transacted_w_address_mean', 'transacted_w_address_median']

First 5 rows:

,address,Time step,num_txs_as_sender,num_txs_as receiver,first_block_appeared_in,last_block_appeared_in,lifetime_in_blocks,total_txs,first_sent_block,first_received_block,num_timesteps_appeared_in,btc_transacted_total,btc_transacted_min,btc_transacted_max,btc_transacted_mean,btc_transacted_median,btc_sent_total,btc_sent_min,btc_sent_max,btc_sent_mean,btc_sent_median,btc_received_total,btc_received_min,btc_received_max,btc_received_mean,btc_received_median,fees_total,fees_min,fees_max,fees_mean,fees_median,fees_as_share_total,fees_as_share_min,fees_as_share_max,fees_as_share_mean,fees_as_share_median,blocks_btwn_txs_total,blocks_btwn_txs_min,blocks_btwn_txs_max,blocks_btwn_txs_mean,blocks_btwn_txs_median,blocks_btwn_input_txs_total,blocks_btwn_input_txs_min,blocks_btwn_input_txs_max,blocks_btwn_input_txs_mean,blocks_btwn_input_txs_median,blocks_btwn_output_txs_total,blocks_btwn_output_txs_min,blocks_btwn_output_txs_max,blocks_btwn_output_txs_mean,blocks_btwn_output_txs_median,num_addr_transacted_multiple,transacted_w_address_total,transacted_w_address_min,transacted_w_address_max,transacted_w_address_mean,transacted_w_address_median
0,111112TykSw72ztDN2WJger4cynzWYC5w,25,0.0,1.0,439586.0,439586.0,0.0,1.0,0.0,439586.0,1.0,0.010628,0.010628,0.010628,0.010628,0.010628,0.0,0.0,0.0,0.0,0.0,0.010628,0.010628,0.010628,0.010628,0.010628,0.007042,0.007042,0.007042,0.007042,0.007042,0.000012,0.000012,0.000012,0.000012,0.000012,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,24.0,1.0,1.0,1.0,1.0
1,1111DAYXhoxZx2tsRnzimfozo783x1yC2,25,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,6.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.0,0.0,0.0,0.0,0.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.002371,0.000122,0.000580,0.000296,0.000242,0.002217,0.000121,0.000523,0.000277,0.000237,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,0.0,0.0,0.0,0.0,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
2,1111DAYXhoxZx2tsRnzimfozo783x1yC2,29,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,6.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.0,0.0,0.0,0.0,0.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.002371,0.000122,0.000580,0.000296,0.000242,0.002217,0.000121,0.000523,0.000277,0.000237,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,0.0,0.0,0.0,0.0,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
3,1111DAYXhoxZx2tsRnzimfozo783x1yC2,39,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,6.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.0,0.0,0.0,0.0,0.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.002371,0.000122,0.000580,0.000296,0.000242,0.002217,0.000121,0.000523,0.000277,0.000237,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,0.0,0.0,0.0,0.0,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
4,1111DAYXhoxZx2tsRnzimfozo783x1yC2,39,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,6.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.0,0.0,0.0,0.0,0.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.002371,0.000122,0.000580,0.000296,0.000242,0.002217,0.000121,0.000523,0.000277,0.000237,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,0.0,0.0,0.0,0.0,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0

============================================================
wallets_classes
File: C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\wallets_classes.csv
Size: 29.01 MB
Columns: 2
Column names:
['address', 'class']

First 5 rows:

                              address  class
0   111112TykSw72ztDN2WJger4cynzWYC5w      2
1   1111DAYXhoxZx2tsRnzimfozo783x1yC2      3
2    1111VHuXEzHaRCgXbVwojtaP7Co3QABb      2
3  111218KKkh1JJFRHbwM16AwCiVCc4m7he1      3
4   1115LWW3xsD9jT9VRY7viCN9S34RVAAuA      2

============================================================
AddrTx_edgelist
File: C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\AddrTx_edgelist.csv
Size: 20.26 MB
Columns: 2
Column names:
['input_address', 'txId']

First 5 rows:

                        input_address       txId
0  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a  230325127
1  13Lhad3SAmu2vqYg2dxbNcxH7LE77kJu2w  230325139
2  1MAQQZn7EHP6J3erXByCciFiVcgS8ZhWqz   86875675
3  16zs5SVSyADh5WrLNbZbpRLsBsN5uEzgeK  230325147
4  1QJpwtUorBKPGUJkSyrRcBKTAHq4CXrdYh  230325154

============================================================
TxAddr_edgelist
File: C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\TxAddr_edgelist.csv
Size: 35.0 MB
Columns: 2
Column names:
['txId', 'output_address']

First 5 rows:

        txId                      output_address
0  230325127  1GASxu5nMntiRKdVtTVRvEbP965G51bhHH
1  230325127  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a
2  230325139  1GFdrdgtG34GChM8SMpMwcXFc4nYbH1A5G
3   86875675  19q57SeCEzTnWrWVXA43nZzhSiXkYggh7c
4   86875675  1Kk1NVYnCE8ALXDhgMM6HqTt1jDSvi6QBA

============================================================
wallets_combined
File: C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\wallets_features_classes_combined.csv
Size: 580.79 MB
Columns: 58
Column names:
['address', 'Time step', 'class', 'num_txs_as_sender', 'num_txs_as receiver', 'first_block_appeared_in', 'last_block_appeared_in', 'lifetime_in_blocks', 'total_txs', 'first_sent_block', 'first_received_block', 'num_timesteps_appeared_in', 'btc_transacted_total', 'btc_transacted_min', 'btc_transacted_max', 'btc_transacted_mean', 'btc_transacted_median', 'btc_sent_total', 'btc_sent_min', 'btc_sent_max', 'btc_sent_mean', 'btc_sent_median', 'btc_received_total', 'btc_received_min', 'btc_received_max', 'btc_received_mean', 'btc_received_median', 'fees_total', 'fees_min', 'fees_max', 'fees_mean', 'fees_median', 'fees_as_share_total', 'fees_as_share_min', 'fees_as_share_max', 'fees_as_share_mean', 'fees_as_share_median', 'blocks_btwn_txs_total', 'blocks_btwn_txs_min', 'blocks_btwn_txs_max', 'blocks_btwn_txs_mean', 'blocks_btwn_txs_median', 'blocks_btwn_input_txs_total', 'blocks_btwn_input_txs_min', 'blocks_btwn_input_txs_max', 'blocks_btwn_input_txs_mean', 'blocks_btwn_input_txs_median', 'blocks_btwn_output_txs_total', 'blocks_btwn_output_txs_min', 'blocks_btwn_output_txs_max', 'blocks_btwn_output_txs_mean', 'blocks_btwn_output_txs_median', 'num_addr_transacted_multiple', 'transacted_w_address_total', 'transacted_w_address_min', 'transacted_w_address_max', 'transacted_w_address_mean', 'transacted_w_address_median']

First 5 rows:

,address,Time step,class,num_txs_as_sender,num_txs_as receiver,first_block_appeared_in,last_block_appeared_in,lifetime_in_blocks,total_txs,first_sent_block,first_received_block,num_timesteps_appeared_in,btc_transacted_total,btc_transacted_min,btc_transacted_max,btc_transacted_mean,btc_transacted_median,btc_sent_total,btc_sent_min,btc_sent_max,btc_sent_mean,btc_sent_median,btc_received_total,btc_received_min,btc_received_max,btc_received_mean,btc_received_median,fees_total,fees_min,fees_max,fees_mean,fees_median,fees_as_share_total,fees_as_share_min,fees_as_share_max,fees_as_share_mean,fees_as_share_median,blocks_btwn_txs_total,blocks_btwn_txs_min,blocks_btwn_txs_max,blocks_btwn_txs_mean,blocks_btwn_txs_median,blocks_btwn_input_txs_total,blocks_btwn_input_txs_min,blocks_btwn_input_txs_max,blocks_btwn_input_txs_mean,blocks_btwn_input_txs_median,blocks_btwn_output_txs_total,blocks_btwn_output_txs_min,blocks_btwn_output_txs_max,blocks_btwn_output_txs_mean,blocks_btwn_output_txs_median,num_addr_transacted_multiple,transacted_w_address_total,transacted_w_address_min,transacted_w_address_max,transacted_w_address_mean,transacted_w_address_median
0,111112TykSw72ztDN2WJger4cynzWYC5w,25,2,0.0,1.0,439586.0,439586.0,0.0,1.0,0.0,439586.0,1.0,0.010628,0.010628,0.010628,0.010628,0.010628,0.0,0.0,0.0,0.0,0.0,0.010628,0.010628,0.010628,0.010628,0.010628,0.007042,0.007042,0.007042,0.007042,0.007042,0.000012,0.000012,0.000012,0.000012,0.000012,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,24.0,1.0,1.0,1.0,1.0
1,1111DAYXhoxZx2tsRnzimfozo783x1yC2,25,3,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,6.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.0,0.0,0.0,0.0,0.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.002371,0.000122,0.000580,0.000296,0.000242,0.002217,0.000121,0.000523,0.000277,0.000237,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,0.0,0.0,0.0,0.0,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
2,1111DAYXhoxZx2tsRnzimfozo783x1yC2,29,3,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,6.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.0,0.0,0.0,0.0,0.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.002371,0.000122,0.000580,0.000296,0.000242,0.002217,0.000121,0.000523,0.000277,0.000237,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,0.0,0.0,0.0,0.0,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
3,1111DAYXhoxZx2tsRnzimfozo783x1yC2,39,3,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,6.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.0,0.0,0.0,0.0,0.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.002371,0.000122,0.000580,0.000296,0.000242,0.002217,0.000121,0.000523,0.000277,0.000237,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,0.0,0.0,0.0,0.0,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0
4,1111DAYXhoxZx2tsRnzimfozo783x1yC2,39,3,0.0,8.0,439589.0,485959.0,46370.0,8.0,0.0,439589.0,6.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.0,0.0,0.0,0.0,0.0,0.273046,0.003900,0.133777,0.034131,0.014352,0.002371,0.000122,0.000580,0.000296,0.000242,0.002217,0.000121,0.000523,0.000277,0.000237,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,0.0,0.0,0.0,0.0,46370.0,0.0,20164.0,6624.285714,8060.0,0.0,8.0,1.0,1.0,1.0,1.0

In [5]:
def count_rows(path):
    total = 0

    for chunk in pd.read_csv(path, chunksize=100_000):
        total += len(chunk)

    return total


for name, path in files.items():
    rows = count_rows(path)

    print(f"{name:25s} : {rows:,} rows")

txs_features              : 203,769 rows
txs_classes               : 203,769 rows
txs_edgelist              : 234,355 rows
wallets_features          : 1,268,260 rows
wallets_classes           : 822,942 rows
AddrTx_edgelist           : 477,117 rows
TxAddr_edgelist           : 837,124 rows
wallets_combined          : 1,268,260 rows

In [7]:
tx_features = pd.read_csv(files["txs_features"])
tx_classes = pd.read_csv(files["txs_classes"])
tx_edges = pd.read_csv(files["txs_edgelist"])

print("Transaction Features:", tx_features.shape)
print("Transaction Classes :", tx_classes.shape)
print("Transaction Edges   :", tx_edges.shape)

Transaction Features: (203769, 184)
Transaction Classes : (203769, 2)
Transaction Edges   : (234355, 2)

In [8]:
print(tx_classes.head())
print(tx_classes.columns)

print("\nClass distribution:")
print(tx_classes.iloc[:, 1].value_counts(dropna=False))

    txId  class
0   3321      3
1  11108      3
2  51816      3
3  68869      2
4  89273      2
Index(['txId', 'class'], dtype='str')

Class distribution:
class
3    157205
2     42019
1      4545
Name: count, dtype: int64

In [9]:
print(tx_edges.head())
print(tx_edges.columns)

       txId1      txId2
0  230425980    5530458
1  232022460  232438397
2  230460314  230459870
3  230333930  230595899
4  232013274  232029206
Index(['txId1', 'txId2'], dtype='str')

In [12]:
print(
    [col for col in tx_features.columns
     if "time" in str(col).lower() or "step" in str(col).lower()]
)

time_col = "Time step"

print(tx_features[time_col].describe())

print(
    tx_features[time_col]
    .value_counts()
    .sort_index()
)

['Time step']
count    203769.000000
mean         23.843961
std          15.172170
min           1.000000
25%           9.000000
50%          23.000000
75%          38.000000
max          49.000000
Name: Time step, dtype: float64
Time step
1     7880
2     4544
3     6621
4     5693
5     6803
6     4328
7     6048
8     4457
9     4996
10    6727
11    4296
12    2047
13    4528
14    2022
15    3639
16    2975
17    3385
18    1976
19    3506
20    4291
21    3537
22    5894
23    4165
24    4592
25    2314
26    2523
27    1089
28    1653
29    4275
30    2483
31    2816
32    4525
33    3151
34    2486
35    5507
36    6393
37    3306
38    2891
39    2760
40    4481
41    5342
42    7140
43    5063
44    4975
45    5598
46    3519
47    5121
48    2954
49    2454
Name: count, dtype: int64

In [13]:
wallet_features = pd.read_csv(files["wallets_features"])
wallet_classes = pd.read_csv(files["wallets_classes"])

print(wallet_features.shape)
print(wallet_classes.shape)

print(wallet_features.head())
print(wallet_classes.head())

(1268260, 57)
(822942, 2)
                             address  Time step  num_txs_as_sender  \
0  111112TykSw72ztDN2WJger4cynzWYC5w         25                0.0
1  1111DAYXhoxZx2tsRnzimfozo783x1yC2         25                0.0
2  1111DAYXhoxZx2tsRnzimfozo783x1yC2         29                0.0
3  1111DAYXhoxZx2tsRnzimfozo783x1yC2         39                0.0
4  1111DAYXhoxZx2tsRnzimfozo783x1yC2         39                0.0

   num_txs_as receiver  first_block_appeared_in  last_block_appeared_in  \
0                  1.0                 439586.0                439586.0
1                  8.0                 439589.0                485959.0
2                  8.0                 439589.0                485959.0
3                  8.0                 439589.0                485959.0
4                  8.0                 439589.0                485959.0

   lifetime_in_blocks  total_txs  first_sent_block  first_received_block  \
0                 0.0        1.0               0.0              439586.0
1             46370.0        8.0               0.0              439589.0
2             46370.0        8.0               0.0              439589.0
3             46370.0        8.0               0.0              439589.0
4             46370.0        8.0               0.0              439589.0

   num_timesteps_appeared_in  btc_transacted_total  btc_transacted_min  \
0                        1.0              0.010628            0.010628
1                        6.0              0.273046            0.003900
2                        6.0              0.273046            0.003900
3                        6.0              0.273046            0.003900
4                        6.0              0.273046            0.003900

   btc_transacted_max  btc_transacted_mean  btc_transacted_median  \
0            0.010628             0.010628               0.010628
1            0.133777             0.034131               0.014352
2            0.133777             0.034131               0.014352
3            0.133777             0.034131               0.014352
4            0.133777             0.034131               0.014352

   btc_sent_total  btc_sent_min  btc_sent_max  btc_sent_mean  btc_sent_median  \
0             0.0           0.0           0.0            0.0              0.0
1             0.0           0.0           0.0            0.0              0.0
2             0.0           0.0           0.0            0.0              0.0
3             0.0           0.0           0.0            0.0              0.0
4             0.0           0.0           0.0            0.0              0.0

   btc_received_total  btc_received_min  btc_received_max  btc_received_mean  \
0            0.010628          0.010628          0.010628           0.010628
1            0.273046          0.003900          0.133777           0.034131
2            0.273046          0.003900          0.133777           0.034131
3            0.273046          0.003900          0.133777           0.034131
4            0.273046          0.003900          0.133777           0.034131

   btc_received_median  fees_total  fees_min  fees_max  fees_mean  \
0             0.010628    0.007042  0.007042  0.007042   0.007042
1             0.014352    0.002371  0.000122  0.000580   0.000296
2             0.014352    0.002371  0.000122  0.000580   0.000296
3             0.014352    0.002371  0.000122  0.000580   0.000296
4             0.014352    0.002371  0.000122  0.000580   0.000296

   fees_median  fees_as_share_total  fees_as_share_min  fees_as_share_max  \
0     0.007042             0.000012           0.000012           0.000012
1     0.000242             0.002217           0.000121           0.000523
2     0.000242             0.002217           0.000121           0.000523
3     0.000242             0.002217           0.000121           0.000523
4     0.000242             0.002217           0.000121           0.000523

   fees_as_share_mean  fees_as_share_median  blocks_btwn_txs_total  \
0            0.000012              0.000012                    0.0
1            0.000277              0.000237                46370.0
2            0.000277              0.000237                46370.0
3            0.000277              0.000237                46370.0
4            0.000277              0.000237                46370.0

   blocks_btwn_txs_min  blocks_btwn_txs_max  blocks_btwn_txs_mean  \
0                  0.0                  0.0              0.000000
1                  0.0              20164.0           6624.285714
2                  0.0              20164.0           6624.285714
3                  0.0              20164.0           6624.285714
4                  0.0              20164.0           6624.285714

   blocks_btwn_txs_median  blocks_btwn_input_txs_total  \
0                     0.0                          0.0
1                  8060.0                          0.0
2                  8060.0                          0.0
3                  8060.0                          0.0
4                  8060.0                          0.0

   blocks_btwn_input_txs_min  blocks_btwn_input_txs_max  \
0                        0.0                        0.0
1                        0.0                        0.0
2                        0.0                        0.0
3                        0.0                        0.0
4                        0.0                        0.0

   blocks_btwn_input_txs_mean  blocks_btwn_input_txs_median  \
0                         0.0                           0.0
1                         0.0                           0.0
2                         0.0                           0.0
3                         0.0                           0.0
4                         0.0                           0.0

   blocks_btwn_output_txs_total  blocks_btwn_output_txs_min  \
0                           0.0                         0.0
1                       46370.0                         0.0
2                       46370.0                         0.0
3                       46370.0                         0.0
4                       46370.0                         0.0

   blocks_btwn_output_txs_max  blocks_btwn_output_txs_mean  \
0                         0.0                     0.000000
1                     20164.0                  6624.285714
2                     20164.0                  6624.285714
3                     20164.0                  6624.285714
4                     20164.0                  6624.285714

   blocks_btwn_output_txs_median  num_addr_transacted_multiple  \
0                            0.0                           0.0
1                         8060.0                           0.0
2                         8060.0                           0.0
3                         8060.0                           0.0
4                         8060.0                           0.0

   transacted_w_address_total  transacted_w_address_min  \
0                        24.0                       1.0
1                         8.0                       1.0
2                         8.0                       1.0
3                         8.0                       1.0
4                         8.0                       1.0

   transacted_w_address_max  transacted_w_address_mean  \
0                       1.0                        1.0
1                       1.0                        1.0
2                       1.0                        1.0
3                       1.0                        1.0
4                       1.0                        1.0

   transacted_w_address_median
0                          1.0
1                          1.0
2                          1.0
3                          1.0
4                          1.0
                              address  class
0   111112TykSw72ztDN2WJger4cynzWYC5w      2
1   1111DAYXhoxZx2tsRnzimfozo783x1yC2      3
2    1111VHuXEzHaRCgXbVwojtaP7Co3QABb      2
3  111218KKkh1JJFRHbwM16AwCiVCc4m7he1      3
4   1115LWW3xsD9jT9VRY7viCN9S34RVAAuA      2

In [15]:
print("TRANSACTION EDGES")
print(tx_edges.head(10))

print("\nADDRESS → TRANSACTION")
addr_tx = pd.read_csv(files["AddrTx_edgelist"])
print(addr_tx.head(10))

print("\nTRANSACTION → ADDRESS")
tx_addr = pd.read_csv(files["TxAddr_edgelist"])
print(tx_addr.head(10))

TRANSACTION EDGES
       txId1      txId2
0  230425980    5530458
1  232022460  232438397
2  230460314  230459870
3  230333930  230595899
4  232013274  232029206
5  232344069   27553029
6   36411953  230405052
7   34194980    5529846
8    3881097  232457116
9  230409257   32877982

ADDRESS → TRANSACTION
                        input_address       txId
0  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a  230325127
1  13Lhad3SAmu2vqYg2dxbNcxH7LE77kJu2w  230325139
2  1MAQQZn7EHP6J3erXByCciFiVcgS8ZhWqz   86875675
3  16zs5SVSyADh5WrLNbZbpRLsBsN5uEzgeK  230325147
4  1QJpwtUorBKPGUJkSyrRcBKTAHq4CXrdYh  230325154
5  15qDzZLrcqQMUh5WnXaHTa4B3kreqAKi36  230325162
6  1HYPEj9ZfUCsoYtbULhH2WyHtBgL3w8MTV  230325162
7   1dtBrLiLzzJx3EGGVo7hc8mB9jxXbfUc6  230325162
8  1JxxNbdHgxwXLw19krxUotkWETLQzGmUFD  230325162
9  19u9iAQhMxRLE8Unksy2xJPawXrxgdsrnv  230325162

TRANSACTION → ADDRESS
        txId                      output_address
0  230325127  1GASxu5nMntiRKdVtTVRvEbP965G51bhHH
1  230325127  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a
2  230325139  1GFdrdgtG34GChM8SMpMwcXFc4nYbH1A5G
3   86875675  19q57SeCEzTnWrWVXA43nZzhSiXkYggh7c
4   86875675  1Kk1NVYnCE8ALXDhgMM6HqTt1jDSvi6QBA
5  230325147  1ExQobam8YdTkwATZjTZgevwrheSkUFVN1
6  230325154  1HHNWMoQ6yVxuBhmnkvLmB3C4mEfZcDD4t
7  230325154  1QJpwtUorBKPGUJkSyrRcBKTAHq4CXrdYh
8  230325162  1E3QGYRS4TQ4FxVhC7FivRXSQHWPaVqSnA
9  230325162  1KiiDJx9DAnyFuqKLaTVJQBc7ov2vrN2id

In [16]:
transaction_ids = set(tx_features["txId"])

edge_source_ids = set(tx_edges["txId1"])
edge_target_ids = set(tx_edges["txId2"])

print("Transaction IDs:", len(transaction_ids))

print(
    "Source IDs found in transaction table:",
    len(edge_source_ids & transaction_ids)
)

print(
    "Target IDs found in transaction table:",
    len(edge_target_ids & transaction_ids)
)

Transaction IDs: 203769
Source IDs found in transaction table: 166345
Target IDs found in transaction table: 148447

In [17]:
print("========== TRANSACTION → TRANSACTION ==========")
print(tx_edges.head(10))

print("\n========== ADDRESS → TRANSACTION ==========")
addr_tx = pd.read_csv(files["AddrTx_edgelist"])
print(addr_tx.head(10))

print("\n========== TRANSACTION → ADDRESS ==========")
tx_addr = pd.read_csv(files["TxAddr_edgelist"])
print(tx_addr.head(10))

========== TRANSACTION → TRANSACTION ==========
       txId1      txId2
0  230425980    5530458
1  232022460  232438397
2  230460314  230459870
3  230333930  230595899
4  232013274  232029206
5  232344069   27553029
6   36411953  230405052
7   34194980    5529846
8    3881097  232457116
9  230409257   32877982

========== ADDRESS → TRANSACTION ==========
                        input_address       txId
0  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a  230325127
1  13Lhad3SAmu2vqYg2dxbNcxH7LE77kJu2w  230325139
2  1MAQQZn7EHP6J3erXByCciFiVcgS8ZhWqz   86875675
3  16zs5SVSyADh5WrLNbZbpRLsBsN5uEzgeK  230325147
4  1QJpwtUorBKPGUJkSyrRcBKTAHq4CXrdYh  230325154
5  15qDzZLrcqQMUh5WnXaHTa4B3kreqAKi36  230325162
6  1HYPEj9ZfUCsoYtbULhH2WyHtBgL3w8MTV  230325162
7   1dtBrLiLzzJx3EGGVo7hc8mB9jxXbfUc6  230325162
8  1JxxNbdHgxwXLw19krxUotkWETLQzGmUFD  230325162
9  19u9iAQhMxRLE8Unksy2xJPawXrxgdsrnv  230325162

========== TRANSACTION → ADDRESS ==========
        txId                      output_address
0  230325127  1GASxu5nMntiRKdVtTVRvEbP965G51bhHH
1  230325127  14YRXHHof4BY1TVxN5FqYPcEdpmXiYT78a
2  230325139  1GFdrdgtG34GChM8SMpMwcXFc4nYbH1A5G
3   86875675  19q57SeCEzTnWrWVXA43nZzhSiXkYggh7c
4   86875675  1Kk1NVYnCE8ALXDhgMM6HqTt1jDSvi6QBA
5  230325147  1ExQobam8YdTkwATZjTZgevwrheSkUFVN1
6  230325154  1HHNWMoQ6yVxuBhmnkvLmB3C4mEfZcDD4t
7  230325154  1QJpwtUorBKPGUJkSyrRcBKTAHq4CXrdYh
8  230325162  1E3QGYRS4TQ4FxVhC7FivRXSQHWPaVqSnA
9  230325162  1KiiDJx9DAnyFuqKLaTVJQBc7ov2vrN2id

In [18]:
print("========== TRANSACTION GRAPH ==========")

print("Unique txId1:",
      tx_edges["txId1"].nunique())

print("Unique txId2:",
      tx_edges["txId2"].nunique())

print("Total edges:",
      len(tx_edges))


print("\n========== ADDRESS → TRANSACTION ==========")

print("Unique input addresses:",
      addr_tx["input_address"].nunique())

print("Unique transactions:",
      addr_tx["txId"].nunique())

print("Total edges:",
      len(addr_tx))


print("\n========== TRANSACTION → ADDRESS ==========")

print("Unique transactions:",
      tx_addr["txId"].nunique())

print("Unique output addresses:",
      tx_addr["output_address"].nunique())

print("Total edges:",
      len(tx_addr))

========== TRANSACTION GRAPH ==========
Unique txId1: 166345
Unique txId2: 148447
Total edges: 234355

========== ADDRESS → TRANSACTION ==========
Unique input addresses: 400212
Unique transactions: 202804
Total edges: 477117

========== TRANSACTION → ADDRESS ==========
Unique transactions: 202804
Unique output addresses: 641043
Total edges: 837124

In [19]:
input_degree = (
    addr_tx
    .groupby("txId")
    .size()
)

print("Input addresses per transaction")
print(input_degree.describe())

print("\nDistribution:")
print(input_degree.value_counts().sort_index().head(20))

Input addresses per transaction
count    202804.000000
mean          2.352602
std          11.952101
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         653.000000
dtype: float64

Distribution:
1     159297
2      22479
3       6436
4       3534
5       2202
6       1517
7        864
8        640
9        600
10       945
11       311
12       224
13       226
14       212
15       183
16       176
17       161
18       171
19       175
20       150
Name: count, dtype: int64

In [20]:
output_degree = (
    tx_addr
    .groupby("txId")
    .size()
)

print("Output addresses per transaction")
print(output_degree.describe())

print("\nDistribution:")
print(output_degree.value_counts().sort_index().head(20))

Output addresses per transaction
count    202804.000000
mean          4.127749
std          49.454645
min           1.000000
25%           2.000000
50%           2.000000
75%           2.000000
max       13107.000000
dtype: float64

Distribution:
1      19128
2     162675
3       5104
4       2092
5       1427
6       1162
7        813
8        745
9        657
10       554
11      1559
12       395
13       350
14       334
15       352
16       890
17       287
18       222
19       218
20       268
Name: count, dtype: int64

In [21]:
source_degree = tx_edges.groupby("txId1").size()
target_degree = tx_edges.groupby("txId2").size()

print("Outgoing transaction connections")
print(source_degree.describe())

print("\nIncoming transaction connections")
print(target_degree.describe())

Outgoing transaction connections
count    166345.000000
mean          1.408849
std           2.008279
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max         472.000000
dtype: float64

Incoming transaction connections
count    148447.000000
mean          1.578712
std           4.507890
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         284.000000
dtype: float64

In [22]:
input_degree = addr_tx.groupby("txId").size()
output_degree = tx_addr.groupby("txId").size()

network_out_degree = tx_edges.groupby("txId1").size()
network_in_degree = tx_edges.groupby("txId2").size()

degree_df = pd.DataFrame({
    "txId": tx_features["txId"]
})

degree_df["input_count"] = degree_df["txId"].map(input_degree).fillna(0)
degree_df["output_count"] = degree_df["txId"].map(output_degree).fillna(0)
degree_df["tx_out_degree"] = degree_df["txId"].map(network_out_degree).fillna(0)
degree_df["tx_in_degree"] = degree_df["txId"].map(network_in_degree).fillna(0)

degree_df.head()

    txId  input_count  output_count  tx_out_degree  tx_in_degree
0   3321          1.0           2.0            0.0           1.0
1  11108          1.0           2.0            1.0           1.0
2  51816          1.0           2.0            1.0           1.0
3  68869          1.0           2.0            1.0           0.0
4  89273          1.0       13107.0          288.0           1.0

In [23]:
degree_df = degree_df.merge(
    tx_classes,
    on="txId",
    how="left"
)

print(degree_df.head())
print(degree_df.columns)

    txId  input_count  output_count  tx_out_degree  tx_in_degree  class
0   3321          1.0           2.0            0.0           1.0      3
1  11108          1.0           2.0            1.0           1.0      3
2  51816          1.0           2.0            1.0           1.0      3
3  68869          1.0           2.0            1.0           0.0      2
4  89273          1.0       13107.0          288.0           1.0      2
Index(['txId', 'input_count', 'output_count', 'tx_out_degree', 'tx_in_degree',
       'class'],
      dtype='str')

In [24]:
print(
    degree_df
    .groupby("class")[
        ["input_count",
         "output_count",
         "tx_out_degree",
         "tx_in_degree"]
    ]
    .describe()
)

      input_count                                                  \
            count      mean        std  min  25%  50%  75%    max
class
1          4545.0  2.749835  19.584092  1.0  1.0  1.0  1.0  500.0
2         42019.0  4.723149  18.875802  0.0  1.0  1.0  3.0  653.0
3        157205.0  1.693057   8.721423  0.0  1.0  1.0  1.0  651.0

      output_count                                                    \
             count      mean        std  min  25%  50%  75%      max
class
1           4545.0  1.352695   0.491035  1.0  1.0  1.0  2.0      9.0
2          42019.0  6.091768  91.718220  0.0  2.0  2.0  2.0  13107.0
3         157205.0  3.657683  30.089202  0.0  2.0  2.0  2.0   2546.0

      tx_out_degree                                                 \
              count      mean       std  min  25%  50%  75%    max
class
1            4545.0  0.741694  0.571620  0.0  0.0  1.0  1.0    3.0
2           42019.0  1.185821  3.246769  0.0  1.0  1.0  1.0  472.0
3          157205.0  1.152362  1.349530  0.0  1.0  1.0  1.0  122.0

      tx_in_degree
             count      mean       std  min  25%  50%  75%    max
class
1           4545.0  1.269967  7.215218  0.0  0.0  1.0  1.0  177.0
2          42019.0  1.909398  7.122538  0.0  0.0  1.0  1.0  284.0
3         157205.0  0.943685  2.136958  0.0  0.0  1.0  1.0  212.0

In [25]:
for c, name in [(1, "ILLICIT"), (2, "LICIT"), (3, "UNKNOWN")]:

    print("\n" + "="*70)
    print(name)

    subset = degree_df[degree_df["class"] == c]

    print("\nHighest input count:")
    print(
        subset.nlargest(10, "input_count")
        [["txId", "input_count", "output_count",
          "tx_out_degree", "tx_in_degree"]]
    )

    print("\nHighest output count:")
    print(
        subset.nlargest(10, "output_count")
        [["txId", "input_count", "output_count",
          "tx_out_degree", "tx_in_degree"]]
    )

    print("\nHighest transaction connectivity:")
    print(
        subset.nlargest(10, "tx_out_degree")
        [["txId", "input_count", "output_count",
          "tx_out_degree", "tx_in_degree"]]
    )

======================================================================
ILLICIT

Highest input count:
             txId  input_count  output_count  tx_out_degree  tx_in_degree
110389  269905671        500.0           1.0            0.0         102.0
190059   75078587        497.0           1.0            0.0          45.0
98709   372745794        461.0           1.0            0.0         139.0
110387  269905668        333.0           1.0            0.0         173.0
111654   84460750        318.0           1.0            1.0          68.0
143342  120019034        309.0           1.0            0.0          43.0
128123  355110272        306.0           1.0            0.0         153.0
150071   30179316        298.0           1.0            0.0         177.0
92319    99675435        293.0           1.0            0.0         158.0
103137  332771446        247.0           1.0            0.0         116.0

Highest output count:
            txId  input_count  output_count  tx_out_degree  tx_in_degree
192499  32054179          1.0           9.0            3.0           0.0
157172  63071445         62.0           3.0            0.0           5.0
189      3205536          5.0           2.0            1.0           0.0
917     16742787          1.0           2.0            1.0           0.0
918     16753577          2.0           2.0            1.0           0.0
919     16754007          2.0           2.0            1.0           0.0
925     17387772          3.0           2.0            1.0           1.0
930     17796937          4.0           2.0            1.0           0.0
1026    24141114          4.0           2.0            1.0           0.0
1027    24155910          2.0           2.0            1.0           0.0

Highest transaction connectivity:
             txId  input_count  output_count  tx_out_degree  tx_in_degree
192499   32054179          1.0           9.0            3.0           0.0
24017   279004203          1.0           2.0            2.0           0.0
37811    94299574          1.0           2.0            2.0           1.0
39953    94654255          1.0           2.0            2.0           1.0
39962    94654271          1.0           2.0            2.0           1.0
42773   189800868          1.0           2.0            2.0           0.0
42842   189984406          1.0           2.0            2.0           1.0
43060   190017287          1.0           2.0            2.0           1.0
44696   191111249          1.0           2.0            2.0           1.0
47015   174759156          1.0           2.0            2.0           0.0

======================================================================
LICIT

Highest input count:
             txId  input_count  output_count  tx_out_degree  tx_in_degree
39843    94640561        653.0           2.0            0.0          78.0
39797    94628333        624.0           2.0            0.0          65.0
150296   30699343        585.0           2.0            0.0         241.0
121242  298740684        582.0           1.0            1.0           0.0
124557  381120031        557.0           2.0            0.0          15.0
7776    234068812        556.0           2.0            2.0           0.0
125640  386095359        550.0           2.0            0.0          39.0
40968    96576418        533.0           1.0            0.0         239.0
39822    94634448        510.0           2.0            0.0          55.0
121244  298740686        498.0           2.0            1.0           0.0

Highest output count:
           txId  input_count  output_count  tx_out_degree  tx_in_degree
4         89273          1.0       13107.0          288.0           1.0
51268    565334          1.0        5341.0           90.0           1.0
94109   2984918          1.0        4912.0          472.0           1.0
133428     3181          1.0        4906.0          112.0           1.0
108696   488266          1.0        4902.0           88.0           1.0
197407     7952          1.0        4667.0           99.0           1.0
64316    459148          6.0        2438.0           41.0           0.0
90572    174370          1.0        2001.0            4.0           1.0
90575    774002          1.0        2001.0           27.0           1.0
90577   2064886          1.0        2001.0           15.0           1.0

Highest transaction connectivity:
           txId  input_count  output_count  tx_out_degree  tx_in_degree
94109   2984918          1.0        4912.0          472.0           1.0
4         89273          1.0       13107.0          288.0           1.0
133428     3181          1.0        4906.0          112.0           1.0
197407     7952          1.0        4667.0           99.0           1.0
51268    565334          1.0        5341.0           90.0           1.0
108696   488266          1.0        4902.0           88.0           1.0
99987   5678249          1.0         974.0           67.0           0.0
99985   3180883          1.0         972.0           51.0           0.0
99988   5689045          1.0         970.0           43.0           0.0
64316    459148          6.0        2438.0           41.0           0.0

======================================================================
UNKNOWN

Highest input count:
             txId  input_count  output_count  tx_out_degree  tx_in_degree
139389   68918808        651.0           1.0            1.0           0.0
149673   29948931        635.0           2.0            2.0           0.0
172390   73357055        621.0           2.0            0.0          57.0
4007    230457202        575.0           1.0            1.0           6.0
150643   38938758        570.0           2.0            1.0           0.0
119183  163879834        559.0           1.0            0.0         102.0
116356   17158862        558.0           2.0            0.0          14.0
89010   209735882        523.0           2.0            1.0           0.0
150642   38926799        515.0           2.0            1.0           0.0
45131   191235246        512.0           2.0            2.0          17.0

Highest output count:
           txId  input_count  output_count  tx_out_degree  tx_in_degree
64315    327038          2.0        2546.0           11.0           0.0
77442   3326918          1.0        2538.0            5.0           1.0
183227   143705          1.0        2512.0           92.0           0.0
90596   9009788          1.0        2501.0            6.0           0.0
153747  1192279          1.0        2493.0           69.0           0.0
113524  1891081          1.0        2474.0           95.0           0.0
77439   2226596          1.0        2459.0           30.0           1.0
62276    411947          1.0        2411.0           48.0           0.0
64326   3583319          1.0        2367.0            4.0           0.0
64319    736448          1.0        2318.0            5.0           0.0

Highest transaction connectivity:
            txId  input_count  output_count  tx_out_degree  tx_in_degree
141351    102570          2.0         787.0          122.0           0.0
113524   1891081          1.0        2474.0           95.0           0.0
183227    143705          1.0        2512.0           92.0           0.0
173360    793584          1.0         527.0           82.0           1.0
156526   4600600          1.0         988.0           76.0           0.0
178279    792948          1.0         554.0           74.0           1.0
141405   3185686          1.0         730.0           72.0           0.0
153747   1192279          1.0        2493.0           69.0           0.0
94165   36460504          1.0         451.0           65.0           1.0
156469    847323          1.0         989.0           64.0           0.0

In [26]:
for c, name in [(1, "ILLICIT"), (2, "LICIT"), (3, "UNKNOWN")]:

    subset = degree_df[degree_df["class"] == c]

    print("\n" + "="*60)
    print(name)

    print(
        subset.nlargest(5, "input_count")
        [["txId", "input_count", "output_count",
          "tx_out_degree", "tx_in_degree"]]
        .to_string(index=False)
    )

    print("\nHighest output count:")
    print(
        subset.nlargest(5, "output_count")
        [["txId", "input_count", "output_count",
          "tx_out_degree", "tx_in_degree"]]
        .to_string(index=False)
    )

    print("\nHighest outgoing degree:")
    print(
        subset.nlargest(5, "tx_out_degree")
        [["txId", "input_count", "output_count",
          "tx_out_degree", "tx_in_degree"]]
        .to_string(index=False)
    )

    print("\nHighest incoming degree:")
    print(
        subset.nlargest(5, "tx_in_degree")
        [["txId", "input_count", "output_count",
          "tx_out_degree", "tx_in_degree"]]
        .to_string(index=False)
    )

============================================================
ILLICIT
     txId  input_count  output_count  tx_out_degree  tx_in_degree
269905671        500.0           1.0            0.0         102.0
 75078587        497.0           1.0            0.0          45.0
372745794        461.0           1.0            0.0         139.0
269905668        333.0           1.0            0.0         173.0
 84460750        318.0           1.0            1.0          68.0

Highest output count:
    txId  input_count  output_count  tx_out_degree  tx_in_degree
32054179          1.0           9.0            3.0           0.0
63071445         62.0           3.0            0.0           5.0
 3205536          5.0           2.0            1.0           0.0
16742787          1.0           2.0            1.0           0.0
16753577          2.0           2.0            1.0           0.0

Highest outgoing degree:
     txId  input_count  output_count  tx_out_degree  tx_in_degree
 32054179          1.0           9.0            3.0           0.0
279004203          1.0           2.0            2.0           0.0
 94299574          1.0           2.0            2.0           1.0
 94654255          1.0           2.0            2.0           1.0
 94654271          1.0           2.0            2.0           1.0

Highest incoming degree:
     txId  input_count  output_count  tx_out_degree  tx_in_degree
 30179316        298.0           1.0            0.0         177.0
269905668        333.0           1.0            0.0         173.0
 96365231        231.0           1.0            0.0         166.0
 99675435        293.0           1.0            0.0         158.0
355110272        306.0           1.0            0.0         153.0

============================================================
LICIT
     txId  input_count  output_count  tx_out_degree  tx_in_degree
 94640561        653.0           2.0            0.0          78.0
 94628333        624.0           2.0            0.0          65.0
 30699343        585.0           2.0            0.0         241.0
298740684        582.0           1.0            1.0           0.0
381120031        557.0           2.0            0.0          15.0

Highest output count:
   txId  input_count  output_count  tx_out_degree  tx_in_degree
  89273          1.0       13107.0          288.0           1.0
 565334          1.0        5341.0           90.0           1.0
2984918          1.0        4912.0          472.0           1.0
   3181          1.0        4906.0          112.0           1.0
 488266          1.0        4902.0           88.0           1.0

Highest outgoing degree:
   txId  input_count  output_count  tx_out_degree  tx_in_degree
2984918          1.0        4912.0          472.0           1.0
  89273          1.0       13107.0          288.0           1.0
   3181          1.0        4906.0          112.0           1.0
   7952          1.0        4667.0           99.0           1.0
 565334          1.0        5341.0           90.0           1.0

Highest incoming degree:
     txId  input_count  output_count  tx_out_degree  tx_in_degree
 43388675        307.0           1.0            0.0         284.0
 68705820        234.0           1.0            0.0         247.0
 30699343        585.0           2.0            0.0         241.0
 96576418        533.0           1.0            0.0         239.0
279187194        190.0           1.0            0.0         211.0

============================================================
UNKNOWN
     txId  input_count  output_count  tx_out_degree  tx_in_degree
 68918808        651.0           1.0            1.0           0.0
 29948931        635.0           2.0            2.0           0.0
 73357055        621.0           2.0            0.0          57.0
230457202        575.0           1.0            1.0           6.0
 38938758        570.0           2.0            1.0           0.0

Highest output count:
   txId  input_count  output_count  tx_out_degree  tx_in_degree
 327038          2.0        2546.0           11.0           0.0
3326918          1.0        2538.0            5.0           1.0
 143705          1.0        2512.0           92.0           0.0
9009788          1.0        2501.0            6.0           0.0
1192279          1.0        2493.0           69.0           0.0

Highest outgoing degree:
   txId  input_count  output_count  tx_out_degree  tx_in_degree
 102570          2.0         787.0          122.0           0.0
1891081          1.0        2474.0           95.0           0.0
 143705          1.0        2512.0           92.0           0.0
 793584          1.0         527.0           82.0           1.0
4600600          1.0         988.0           76.0           0.0

Highest incoming degree:
     txId  input_count  output_count  tx_out_degree  tx_in_degree
225859042        260.0           2.0            0.0         212.0
234890810        196.0           1.0            0.0         199.0
225711361        376.0           1.0            0.0         167.0
121654821        182.0           2.0            2.0         154.0
355174807         18.0           2.0            1.0         142.0

In [27]:
target_tx = 230325162

print("========== INPUT ADDRESSES ==========")

inputs = addr_tx[
    addr_tx["txId"] == target_tx
]

print(inputs.to_string(index=False))


print("\n========== OUTPUT ADDRESSES ==========")

outputs = tx_addr[
    tx_addr["txId"] == target_tx
]

print(outputs.to_string(index=False))


print("\n========== PREVIOUS TRANSACTIONS ==========")

previous_txs = tx_edges[
    tx_edges["txId2"] == target_tx
]

print(previous_txs.to_string(index=False))


print("\n========== NEXT TRANSACTIONS ==========")

next_txs = tx_edges[
    tx_edges["txId1"] == target_tx
]

print(next_txs.to_string(index=False))

========== INPUT ADDRESSES ==========
                     input_address      txId
15qDzZLrcqQMUh5WnXaHTa4B3kreqAKi36 230325162
1HYPEj9ZfUCsoYtbULhH2WyHtBgL3w8MTV 230325162
 1dtBrLiLzzJx3EGGVo7hc8mB9jxXbfUc6 230325162
1JxxNbdHgxwXLw19krxUotkWETLQzGmUFD 230325162
19u9iAQhMxRLE8Unksy2xJPawXrxgdsrnv 230325162
1DN3MfRt6M4dm5DepeDeFfZvbLL45vtn6P 230325162

========== OUTPUT ADDRESSES ==========
     txId                     output_address
230325162 1E3QGYRS4TQ4FxVhC7FivRXSQHWPaVqSnA
230325162 1KiiDJx9DAnyFuqKLaTVJQBc7ov2vrN2id

========== PREVIOUS TRANSACTIONS ==========
Empty DataFrame
Columns: [txId1, txId2]
Index: []

========== NEXT TRANSACTIONS ==========
    txId1     txId2
230325162 230602580

In [28]:
tx_a = 230325162
tx_b = 230602580

print("========== TX A INPUTS ==========")
print(
    addr_tx[addr_tx["txId"] == tx_a]
    .to_string(index=False)
)

print("\n========== TX A OUTPUTS ==========")
print(
    tx_addr[tx_addr["txId"] == tx_a]
    .to_string(index=False)
)

print("\n========== TX B INPUTS ==========")
print(
    addr_tx[addr_tx["txId"] == tx_b]
    .to_string(index=False)
)

print("\n========== TX B OUTPUTS ==========")
print(
    tx_addr[tx_addr["txId"] == tx_b]
    .to_string(index=False)
)

========== TX A INPUTS ==========
                     input_address      txId
15qDzZLrcqQMUh5WnXaHTa4B3kreqAKi36 230325162
1HYPEj9ZfUCsoYtbULhH2WyHtBgL3w8MTV 230325162
 1dtBrLiLzzJx3EGGVo7hc8mB9jxXbfUc6 230325162
1JxxNbdHgxwXLw19krxUotkWETLQzGmUFD 230325162
19u9iAQhMxRLE8Unksy2xJPawXrxgdsrnv 230325162
1DN3MfRt6M4dm5DepeDeFfZvbLL45vtn6P 230325162

========== TX A OUTPUTS ==========
     txId                     output_address
230325162 1E3QGYRS4TQ4FxVhC7FivRXSQHWPaVqSnA
230325162 1KiiDJx9DAnyFuqKLaTVJQBc7ov2vrN2id

========== TX B INPUTS ==========
                     input_address      txId
1KCR5f4vfPX8BKVVMuDETbUg7oJL65jrSh 230602580
1E3QGYRS4TQ4FxVhC7FivRXSQHWPaVqSnA 230602580
12AWeCqBBGQJZ5nNzqSyjQNE6sHTQQLvx3 230602580
12XdhEjAQR4rg1RzmXzyPoX5dCrQ9BXfMF 230602580

========== TX B OUTPUTS ==========
     txId                     output_address
230602580 1GAf1BipujKJPaZak7MbmHELbtPuPhAHrK
230602580 1HaPpbyk9zUkEMm3nS8nCmCwCmJwFHd2dQ

In [29]:
print("Number of transaction columns:", len(tx_features.columns))

for i, col in enumerate(tx_features.columns):
    print(i, ":", col)

Number of transaction columns: 184
0 : txId
1 : Time step
2 : Local_feature_1
3 : Local_feature_2
4 : Local_feature_3
5 : Local_feature_4
6 : Local_feature_5
7 : Local_feature_6
8 : Local_feature_7
9 : Local_feature_8
10 : Local_feature_9
11 : Local_feature_10
12 : Local_feature_11
13 : Local_feature_12
14 : Local_feature_13
15 : Local_feature_14
16 : Local_feature_15
17 : Local_feature_16
18 : Local_feature_17
19 : Local_feature_18
20 : Local_feature_19
21 : Local_feature_20
22 : Local_feature_21
23 : Local_feature_22
24 : Local_feature_23
25 : Local_feature_24
26 : Local_feature_25
27 : Local_feature_26
28 : Local_feature_27
29 : Local_feature_28
30 : Local_feature_29
31 : Local_feature_30
32 : Local_feature_31
33 : Local_feature_32
34 : Local_feature_33
35 : Local_feature_34
36 : Local_feature_35
37 : Local_feature_36
38 : Local_feature_37
39 : Local_feature_38
40 : Local_feature_39
41 : Local_feature_40
42 : Local_feature_41
43 : Local_feature_42
44 : Local_feature_43
45 : Local_feature_44
46 : Local_feature_45
47 : Local_feature_46
48 : Local_feature_47
49 : Local_feature_48
50 : Local_feature_49
51 : Local_feature_50
52 : Local_feature_51
53 : Local_feature_52
54 : Local_feature_53
55 : Local_feature_54
56 : Local_feature_55
57 : Local_feature_56
58 : Local_feature_57
59 : Local_feature_58
60 : Local_feature_59
61 : Local_feature_60
62 : Local_feature_61
63 : Local_feature_62
64 : Local_feature_63
65 : Local_feature_64
66 : Local_feature_65
67 : Local_feature_66
68 : Local_feature_67
69 : Local_feature_68
70 : Local_feature_69
71 : Local_feature_70
72 : Local_feature_71
73 : Local_feature_72
74 : Local_feature_73
75 : Local_feature_74
76 : Local_feature_75
77 : Local_feature_76
78 : Local_feature_77
79 : Local_feature_78
80 : Local_feature_79
81 : Local_feature_80
82 : Local_feature_81
83 : Local_feature_82
84 : Local_feature_83
85 : Local_feature_84
86 : Local_feature_85
87 : Local_feature_86
88 : Local_feature_87
89 : Local_feature_88
90 : Local_feature_89
91 : Local_feature_90
92 : Local_feature_91
93 : Local_feature_92
94 : Local_feature_93
95 : Aggregate_feature_1
96 : Aggregate_feature_2
97 : Aggregate_feature_3
98 : Aggregate_feature_4
99 : Aggregate_feature_5
100 : Aggregate_feature_6
101 : Aggregate_feature_7
102 : Aggregate_feature_8
103 : Aggregate_feature_9
104 : Aggregate_feature_10
105 : Aggregate_feature_11
106 : Aggregate_feature_12
107 : Aggregate_feature_13
108 : Aggregate_feature_14
109 : Aggregate_feature_15
110 : Aggregate_feature_16
111 : Aggregate_feature_17
112 : Aggregate_feature_18
113 : Aggregate_feature_19
114 : Aggregate_feature_20
115 : Aggregate_feature_21
116 : Aggregate_feature_22
117 : Aggregate_feature_23
118 : Aggregate_feature_24
119 : Aggregate_feature_25
120 : Aggregate_feature_26
121 : Aggregate_feature_27
122 : Aggregate_feature_28
123 : Aggregate_feature_29
124 : Aggregate_feature_30
125 : Aggregate_feature_31
126 : Aggregate_feature_32
127 : Aggregate_feature_33
128 : Aggregate_feature_34
129 : Aggregate_feature_35
130 : Aggregate_feature_36
131 : Aggregate_feature_37
132 : Aggregate_feature_38
133 : Aggregate_feature_39
134 : Aggregate_feature_40
135 : Aggregate_feature_41
136 : Aggregate_feature_42
137 : Aggregate_feature_43
138 : Aggregate_feature_44
139 : Aggregate_feature_45
140 : Aggregate_feature_46
141 : Aggregate_feature_47
142 : Aggregate_feature_48
143 : Aggregate_feature_49
144 : Aggregate_feature_50
145 : Aggregate_feature_51
146 : Aggregate_feature_52
147 : Aggregate_feature_53
148 : Aggregate_feature_54
149 : Aggregate_feature_55
150 : Aggregate_feature_56
151 : Aggregate_feature_57
152 : Aggregate_feature_58
153 : Aggregate_feature_59
154 : Aggregate_feature_60
155 : Aggregate_feature_61
156 : Aggregate_feature_62
157 : Aggregate_feature_63
158 : Aggregate_feature_64
159 : Aggregate_feature_65
160 : Aggregate_feature_66
161 : Aggregate_feature_67
162 : Aggregate_feature_68
163 : Aggregate_feature_69
164 : Aggregate_feature_70
165 : Aggregate_feature_71
166 : Aggregate_feature_72
167 : in_txs_degree
168 : out_txs_degree
169 : total_BTC
170 : fees
171 : size
172 : num_input_addresses
173 : num_output_addresses
174 : in_BTC_min
175 : in_BTC_max
176 : in_BTC_mean
177 : in_BTC_median
178 : in_BTC_total
179 : out_BTC_min
180 : out_BTC_max
181 : out_BTC_mean
182 : out_BTC_median
183 : out_BTC_total

In [30]:
print(tx_features.dtypes.value_counts())

print("\nFirst 5 rows:")
display(tx_features.head())

float64    182
int64        2
Name: count, dtype: int64

First 5 rows:

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,Local_feature_9,Local_feature_10,Local_feature_11,Local_feature_12,Local_feature_13,Local_feature_14,Local_feature_15,Local_feature_16,Local_feature_17,Local_feature_18,Local_feature_19,Local_feature_20,Local_feature_21,Local_feature_22,Local_feature_23,Local_feature_24,Local_feature_25,Local_feature_26,Local_feature_27,Local_feature_28,Local_feature_29,Local_feature_30,Local_feature_31,Local_feature_32,Local_feature_33,Local_feature_34,Local_feature_35,Local_feature_36,Local_feature_37,Local_feature_38,Local_feature_39,Local_feature_40,Local_feature_41,Local_feature_42,Local_feature_43,Local_feature_44,Local_feature_45,Local_feature_46,Local_feature_47,Local_feature_48,Local_feature_49,Local_feature_50,Local_feature_51,Local_feature_52,Local_feature_53,Local_feature_54,Local_feature_55,Local_feature_56,Local_feature_57,Local_feature_58,Local_feature_59,Local_feature_60,Local_feature_61,Local_feature_62,Local_feature_63,Local_feature_64,Local_feature_65,Local_feature_66,Local_feature_67,Local_feature_68,Local_feature_69,Local_feature_70,Local_feature_71,Local_feature_72,Local_feature_73,Local_feature_74,Local_feature_75,Local_feature_76,Local_feature_77,Local_feature_78,Local_feature_79,Local_feature_80,Local_feature_81,Local_feature_82,Local_feature_83,Local_feature_84,Local_feature_85,Local_feature_86,Local_feature_87,Local_feature_88,Local_feature_89,Local_feature_90,Local_feature_91,Local_feature_92,Local_feature_93,Aggregate_feature_1,Aggregate_feature_2,Aggregate_feature_3,Aggregate_feature_4,Aggregate_feature_5,Aggregate_feature_6,Aggregate_feature_7,Aggregate_feature_8,Aggregate_feature_9,Aggregate_feature_10,Aggregate_feature_11,Aggregate_feature_12,Aggregate_feature_13,Aggregate_feature_14,Aggregate_feature_15,Aggregate_feature_16,Aggregate_feature_17,Aggregate_feature_18,Aggregate_feature_19,Aggregate_feature_20,Aggregate_feature_21,Aggregate_feature_22,Aggregate_feature_23,Aggregate_feature_24,Aggregate_feature_25,Aggregate_feature_26,Aggregate_feature_27,Aggregate_feature_28,Aggregate_feature_29,Aggregate_feature_30,Aggregate_feature_31,Aggregate_feature_32,Aggregate_feature_33,Aggregate_feature_34,Aggregate_feature_35,Aggregate_feature_36,Aggregate_feature_37,Aggregate_feature_38,Aggregate_feature_39,Aggregate_feature_40,Aggregate_feature_41,Aggregate_feature_42,Aggregate_feature_43,Aggregate_feature_44,Aggregate_feature_45,Aggregate_feature_46,Aggregate_feature_47,Aggregate_feature_48,Aggregate_feature_49,Aggregate_feature_50,Aggregate_feature_51,Aggregate_feature_52,Aggregate_feature_53,Aggregate_feature_54,Aggregate_feature_55,Aggregate_feature_56,Aggregate_feature_57,Aggregate_feature_58,Aggregate_feature_59,Aggregate_feature_60,Aggregate_feature_61,Aggregate_feature_62,Aggregate_feature_63,Aggregate_feature_64,Aggregate_feature_65,Aggregate_feature_66,Aggregate_feature_67,Aggregate_feature_68,Aggregate_feature_69,Aggregate_feature_70,Aggregate_feature_71,Aggregate_feature_72,in_txs_degree,out_txs_degree,total_BTC,fees,size,num_input_addresses,num_output_addresses,in_BTC_min,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total
0,3321,1,-0.169615,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160199,-0.166062,-0.049707,-0.162507,-0.028741,-0.035391,-0.042955,-0.013282,-0.042183,-0.168770,-0.171416,-0.172277,-1.373657,-1.371460,-0.139663,-0.148869,-0.080147,-0.155604,-0.010763,-0.012107,-0.139665,-0.148864,-0.080147,-0.155604,-0.010669,-0.012005,-0.024668,-0.031272,-0.023045,-0.026214,0.001428,0.001483,-0.226298,-0.238504,-0.075256,-0.234053,0.037468,0.043444,-0.226681,-0.242726,-0.097895,-0.235378,0.036577,0.042345,1.830780,1.378639,-0.232553,1.686410,0.048767,0.052956,-0.038877,-0.172804,-0.163071,-0.160801,-1.316342,-1.315388,-0.038872,-0.172793,-0.163060,-0.160794,-1.316333,-1.315375,-0.017032,-0.030026,-0.017640,-0.015071,2.146899,2.148396,-0.093535,-0.263634,-0.249970,-0.262749,1.133527,1.135947,-0.057425,-0.261929,-0.254785,-0.258624,1.125590,1.128038,-0.087322,0.780884,1.079939,0.722695,1.135523,1.135279,-0.168245,-0.200866,-0.116817,-0.190577,-0.014659,-0.018849,-1.457761,-1.493861,-0.083459,-1.485777,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.02606,-0.02766,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.106963,-0.179531,-0.166280,-0.187518,-1.159649,-1.160129,-1.371865,-1.352048,-0.295364,-1.401266,-0.975738,-0.975237,-0.158413,-0.451760,-0.420758,-0.430701,-1.015963,-1.016230,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.003773,-0.562664,-0.577099,-0.500080,0.241128,0.241406,-0.098889,-0.087490,-0.084674,-0.140597,1.519700,1.521399,1.0,0.0,0.533972,0.0001,225.0,1.0,2.0,0.534072,0.534072,0.534072,0.534072,0.534072,1.668990e-01,0.367074,0.266986,0.266986,0.533972
1,11108,1,-0.137586,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.127429,-0.133751,-0.049707,-0.129773,-0.028741,-0.035391,-0.042955,-0.013282,-0.003952,-0.138560,-0.139821,-0.134358,0.887058,0.884557,-0.139564,-0.148805,-0.080147,-0.155520,-0.010763,-0.012107,-0.139566,-0.148800,-0.080147,-0.155520,-0.010669,-0.012005,-0.024530,-0.031142,-0.023045,-0.026079,0.001428,0.001483,-0.226837,-0.239012,-0.075256,-0.234581,0.037468,0.043444,-0.226829,-0.242870,-0.097895,-0.235524,0.036577,0.042345,-0.288031,-0.383568,-0.232553,-0.346677,0.048767,0.052956,-0.038480,-0.172741,-0.163066,-0.160680,-1.316342,-1.315388,-0.038476,-0.172730,-0.163055,-0.160674,-1.316333,-1.315375,-0.017017,-0.029960,-0.017570,-0.015001,2.146899,2.148396,-0.092415,-0.262615,-0.249047,-0.261598,-1.471764,-1.470277,-0.054370,-0.261799,-0.254890,-0.258254,-1.499972,-1.498585,-0.057942,-0.240245,-0.168005,-0.178427,-1.084907,-1.084845,-0.147555,-0.184622,-0.116817,-0.170331,-0.014659,-0.018849,-1.457825,-1.493927,-0.083459,-1.485842,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.02606,-0.02766,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.100250,-0.185437,-0.175308,-0.192920,1.064205,1.063787,-1.373782,-1.352048,-0.290966,-1.402204,-0.975738,-0.975237,-0.168742,-0.429352,-0.389444,-0.412059,-1.015963,-1.016230,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.216814,-0.605631,-0.562153,-0.600999,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792,1.0,1.0,5.611778,0.0001,225.0,1.0,2.0,5.611878,5.611878,5.611878,5.611878,5.611878,5.861940e-01,5.025584,2.805889,2.805889,5.611778
2,51816,1,-0.170103,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160699,-0.166555,-0.049707,-0.163006,-0.028741,-0.035391,-0.042955,-0.013282,-0.036613,-0.169668,-0.172904,-0.172855,-1.373657,-1.371460,-0.139731,-0.148912,-0.080147,-0.155661,-0.010763,-0.012107,-0.139732,-0.148907,-0.080147,-0.155661,-0.010669,-0.012005,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227215,-0.239368,-0.075256,-0.234952,0.037468,0.043444,-0.227203,-0.243236,-0.097895,-0.235896,0.036577,0.042345,-0.414002,-0.488337,-0.232553,-0.467551,0.048767,0.052956,-0.039149,-0.172893,-0.163124,-0.160931,-1.316342,-1.315388,-0.039144,-0.172882,-0.163113,-0.160924,-1.316333,-1.315375,-0.017032,-0.029966,-0.017576,-0.015008,-2.428426,-2.429065,-0.095403,-0.264074,-0.250213,-0.263399,-1.471764,-1.470277,-0.059013,-0.262228,-0.254967,-0.259052,-1.499972,-1.498585,-0.293754,1.026982,1.469183,0.874614,-1.084907,-1.084845,-0.169178,-0.201598,-0.116817,-0.191490,-0.014659,-0.018849,-1.458049,-1.494155,-0.083459,-1.486069,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.02606,-0.02766,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.121111,-0.199742,-0.188714,-0.213667,-1.159649,-1.160129,-1.373902,-1.352048,-0.290691,-1.402262,-0.975738,-0.975237,-0.168742,-0.458162,-0.424672,-0.440022,0.143001,0.142525,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.216814,-0.617907,-0.577099,-0.613614,0.241128,0.241406,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792,1.0,1.0,0.456508,0.0001,226.0,1.0,2.0,0.456608,0.456608,0.456608,0.456608,0.456608,2.279902e-01,0.228518,0.228254,0.228254,0.456508
3,68869,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,-0.118555,0.300047,-0.145947,2.017758,1.189967,-0.042955,-0.013282,0.054659,-0.118754,-0.121849,-0.106751,-1.373657,-1.371460,-0.139302,-0.148638,-0.080147,-0.155297,-0.010763,-0.012107,-0.139303,-0.148633,-0.080147,-0.155297,-0.010669,-0.012005,-0.024667,-0.031270,-0.023045,-0.026213,0.001428,0.001483,-0.225929,-0.238157,-0.075256,-0.233692,0.037468,0.043444,-0.226790,-0.242832,-0.097895,-0.235485,0.036577,0.042345,1.779449,1.335947,-0.232553,1.637156,0.048767,0.052956,-0.038211,-0.172643,-0.163004,-0.160543,0.923473,0.923011,-0.038207,-0.172632,-0.162993,-0.160536,0.923516,0.923110,-0.017032,-0.030025,-0.017639,-0.015070,2.146899,2.148396,-0.094058,-0.263316,-0.249584,-0.262486,1.133527,1.135947,-0.056814,-0.262032,-0.254938,-0.258681,1.125590,1.128038,1.056058,0.745604,0.529777,1.065507,1.135523,1.135279,-0.169418,-0.173724,-0.056760,-0.179202,2.105260,1.256720,-1.624659,-1.495881,1.607475,-1.543580,-0.086866,1.339449,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.115534,-0.021730,-0.087925,-0.02606,-0.02766,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.104489,-0.173559,-0.159261,-0.180144,-1.159649,-1.160129,-1.373723,-1.352048,-0.291104,-1.402174,1.342003,1.340733,-0.168742,-0.458162,-0.424672,-0.440022,0.143001,0.142525,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.216814,-0.611769,-0.569626,-0.607306,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792,0.0,1.0,9.308800,0.0001,853.0,3.0,2.0,0.308900,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800
4,89273,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,5.252974,-0.049707,5.327423,-0.028741,-0.035391,265.263236,-0.013282,-0.057401,0.096439,-0.167593,-0.175293,-0.474922,-1.371460,1.828567,1.107041,-0.080147,1.512162,-0.010763,-0.012107,1.828864,1.107130,-0.080147,1.512340,-0.010669,-0.012005,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.210772,-0.223886,-0.075256,-0.218857,0.037468,0.043444,-0.210158,-0.226564,-0.097895,-0.218953,0.036577,0.042345,6.068082,4.902787,-0.232553,5.752276,0.048767,0.052956,-0.039151,-0.091613,-0.161502,-0.160686,-0.264758,-0.707181,-0.039146,-0.091595,-0.161492,-0.160680,-0.264359,-0.702900,-0.017032,3.203811,0.025727,-0.013853,-0.175326,0.184296,-0.095403,-0.197997,-0.246099,-0.258120,-0.652569,-0.822931,-0.059135,-0.227441,-0.251673,-0.255840,-0.756654,-0.846083,-0.293897,5.105231,0.736121,1.871421,-0.090956,-0.100024,10.440725,8.127848,-0.116817,10.190558,-0.014659,-0.018849,-1.458081,-1.494187,-0.083459,-1.486102,-0.088798,-0.090437,-0.177664,-0.224985,-0.134546,-0.205434,-0.003175,-0.004094,-1.626385,-1.781034,-0.349933,-1.772827,-0.004358,-0.004194,2.809553,1.533707,-0.137323,2.558191,-0.02606,-0.02766,-0.064170,-0.126676,-0.097719,-0.103061,0.003143,0.002426,-0.124895,5.678743,0.801359,0.091790,-0.050514,-0.370849,-1.373902,3.443178,2.517666,-1.043190,0.471949,0.605886,-0.179070,2.739765,-0.021386,-0.245374,0.064599,0.030362,-1.511910,1.192421,1.085161,-0.222904,0.094796,0.084615,-0.216814,4.010246,1.258630,0.982479,0.118347,0.091066,-0.098889,0.854508,-0.066727,-0.150067,-0.080760,-0.070977,1.0,288.0,852.164680,0.0000,445268.0,1.0,13107.0,852.164680,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680

In [3]:
# ============================================================
# FEATURE AUDIT
# ============================================================

import pandas as pd
import numpy as np

tx_features = pd.read_csv("C:/Users/koush/OneDrive/Documents/Financial_Forensics/data/raw/eliptic++/txs_features.csv")

print("Transaction feature dataset loaded successfully.")
print("Shape:", tx_features.shape)

tx_features.head()

Transaction feature dataset loaded successfully.
Shape: (203769, 184)

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,...,in_BTC_min,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total
0,3321,1,-0.169615,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160199,...,0.534072,0.534072,0.534072,0.534072,0.534072,1.668990e-01,0.367074,0.266986,0.266986,0.533972
1,11108,1,-0.137586,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.127429,...,5.611878,5.611878,5.611878,5.611878,5.611878,5.861940e-01,5.025584,2.805889,2.805889,5.611778
2,51816,1,-0.170103,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160699,...,0.456608,0.456608,0.456608,0.456608,0.456608,2.279902e-01,0.228518,0.228254,0.228254,0.456508
3,68869,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,...,0.308900,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800
4,89273,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,...,852.164680,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680

In [4]:
# Feature columns

feature_cols = [
    col for col in tx_features.columns
    if col != "txId"
]

print("Total columns:", len(tx_features.columns))
print("Identifier column: txId")
print("Feature columns:", len(feature_cols))

print("\nFirst 10 feature columns:")
print(feature_cols[:10])

print("\nLast 10 feature columns:")
print(feature_cols[-10:])

Total columns: 184
Identifier column: txId
Feature columns: 183

First 10 feature columns:
['Time step', 'Local_feature_1', 'Local_feature_2', 'Local_feature_3', 'Local_feature_4', 'Local_feature_5', 'Local_feature_6', 'Local_feature_7', 'Local_feature_8', 'Local_feature_9']

Last 10 feature columns:
['in_BTC_min', 'in_BTC_max', 'in_BTC_mean', 'in_BTC_median', 'in_BTC_total', 'out_BTC_min', 'out_BTC_max', 'out_BTC_mean', 'out_BTC_median', 'out_BTC_total']

In [5]:
# ============================================================
# DATA TYPE AUDIT
# ============================================================

print("Data types of all columns:")
print(tx_features.dtypes.value_counts())

print("\nNon-numeric columns:")
non_numeric_cols = tx_features.select_dtypes(
    exclude=np.number
).columns.tolist()

print(non_numeric_cols)

print("\nNumeric columns:")
numeric_cols = tx_features.select_dtypes(
    include=np.number
).columns.tolist()

print("Number of numeric columns:", len(numeric_cols))

Data types of all columns:
float64    182
int64        2
Name: count, dtype: int64

Non-numeric columns:
[]

Numeric columns:
Number of numeric columns: 184

In [6]:
# ============================================================
# MISSING VALUE AUDIT
# ============================================================

missing_count = tx_features[feature_cols].isnull().sum()

missing_summary = pd.DataFrame({
    "Feature": missing_count.index,
    "Missing_Count": missing_count.values,
    "Missing_Percentage": (
        missing_count.values / len(tx_features) * 100
    )
})

missing_summary = missing_summary.sort_values(
    "Missing_Count",
    ascending=False
)

print("Total missing values:",
      missing_summary["Missing_Count"].sum())

print("\nFeatures containing missing values:")

display(
    missing_summary[
        missing_summary["Missing_Count"] > 0
    ]
)

Total missing values: 16405

Features containing missing values:

                  Feature  Missing_Count  Missing_Percentage
176         in_BTC_median            965            0.473575
177          in_BTC_total            965            0.473575
178           out_BTC_min            965            0.473575
179           out_BTC_max            965            0.473575
180          out_BTC_mean            965            0.473575
181        out_BTC_median            965            0.473575
167        out_txs_degree            965            0.473575
166         in_txs_degree            965            0.473575
168             total_BTC            965            0.473575
169                  fees            965            0.473575
170                  size            965            0.473575
171   num_input_addresses            965            0.473575
172  num_output_addresses            965            0.473575
173            in_BTC_min            965            0.473575
174            in_BTC_max            965            0.473575
175           in_BTC_mean            965            0.473575
182         out_BTC_total            965            0.473575

In [7]:
# ============================================================
# CONSTANT / NEAR-CONSTANT FEATURE AUDIT
# ============================================================

constant_features = []

near_constant_features = []

for col in feature_cols:

    value_counts = tx_features[col].value_counts(
        normalize=True,
        dropna=False
    )

    unique_values = tx_features[col].nunique(
        dropna=True
    )

    top_percentage = (
        value_counts.iloc[0] * 100
        if len(value_counts) > 0
        else 0
    )

    # Completely constant
    if unique_values <= 1:

        constant_features.append({
            "Feature": col,
            "Unique_Values": unique_values,
            "Top_Value_Percentage": top_percentage
        })

    # >= 99.5% same value
    elif top_percentage >= 99.5:

        near_constant_features.append({
            "Feature": col,
            "Unique_Values": unique_values,
            "Top_Value_Percentage": top_percentage
        })


constant_df = pd.DataFrame(constant_features)

near_constant_df = pd.DataFrame(
    near_constant_features
)

print("Number of constant features:",
      len(constant_df))

print("Number of near-constant features:",
      len(near_constant_df))


print("\nConstant features:")
display(constant_df)


print("\nNear-constant features:")
display(near_constant_df)

Number of constant features: 0
Number of near-constant features: 1

Constant features:

Empty DataFrame
Columns: []
Index: []

Near-constant features:

            Feature  Unique_Values  Top_Value_Percentage
0  Local_feature_15             51              99.84983

In [8]:
# ============================================================
# INVESTIGATE MISSING AUGMENTED FEATURES
# ============================================================

augmented_cols = [
    col for col in tx_features.columns
    if col in [
        "in_txs_degree",
        "out_txs_degree",
        "total_BTC",
        "fees",
        "size",
        "num_input_addresses",
        "num_output_addresses",
        "in_BTC_min",
        "in_BTC_max",
        "in_BTC_mean",
        "in_BTC_median",
        "in_BTC_total",
        "out_BTC_min",
        "out_BTC_max",
        "out_BTC_mean",
        "out_BTC_median",
        "out_BTC_total"
    ]
]

print("Elliptic++ augmented features found:")
print(augmented_cols)

print("\nNumber of augmented features:",
      len(augmented_cols))


# ------------------------------------------------------------
# Find transactions where augmented features are missing
# ------------------------------------------------------------

missing_augmented = tx_features[
    tx_features[augmented_cols].isna().all(axis=1)
].copy()

print("\nTransactions missing ALL augmented features:",
      len(missing_augmented))


# ------------------------------------------------------------
# Check their time-step distribution
# ------------------------------------------------------------

print("\nTime-step distribution of missing transactions:")

missing_time_steps = (
    missing_augmented["Time step"]
    .value_counts()
    .sort_index()
)

display(missing_time_steps.to_frame(
    name="Missing_Transactions"
))


# ------------------------------------------------------------
# Compare with total transactions per time step
# ------------------------------------------------------------

total_by_time = (
    tx_features["Time step"]
    .value_counts()
    .sort_index()
)

time_comparison = pd.DataFrame({

    "Total_Transactions":
        total_by_time,

    "Missing_Augmented":
        missing_time_steps

}).fillna(0)

time_comparison["Missing_Percentage"] = (
    time_comparison["Missing_Augmented"]
    / time_comparison["Total_Transactions"]
    * 100
)

print("\nMissing augmented features by time step:")

display(time_comparison)

Elliptic++ augmented features found:
['in_txs_degree', 'out_txs_degree', 'total_BTC', 'fees', 'size', 'num_input_addresses', 'num_output_addresses', 'in_BTC_min', 'in_BTC_max', 'in_BTC_mean', 'in_BTC_median', 'in_BTC_total', 'out_BTC_min', 'out_BTC_max', 'out_BTC_mean', 'out_BTC_median', 'out_BTC_total']

Number of augmented features: 17

Transactions missing ALL augmented features: 965

Time-step distribution of missing transactions:

           Missing_Transactions
Time step
1                            36
2                            15
4                             4
5                             2
7                            22
8                            26
9                             5
11                            7
12                            8
13                           12
14                            2
15                           16
16                           12
17                           12
18                            7
20                            4
21                            3
22                           16
23                           33
24                           12
25                            7
26                            4
27                           12
28                            1
29                            9
30                            8
31                           41
32                           12
33                            3
34                           50
35                           21
36                          117
37                           62
38                           17
39                           43
40                           23
41                           30
42                           15
43                          144
44                           23
45                           40
46                            7
47                           16
49                            6

Missing augmented features by time step:

           Total_Transactions  Missing_Augmented  Missing_Percentage
Time step
1                        7880               36.0            0.456853
2                        4544               15.0            0.330106
3                        6621                0.0            0.000000
4                        5693                4.0            0.070262
5                        6803                2.0            0.029399
6                        4328                0.0            0.000000
7                        6048               22.0            0.363757
8                        4457               26.0            0.583352
9                        4996                5.0            0.100080
10                       6727                0.0            0.000000
11                       4296                7.0            0.162942
12                       2047                8.0            0.390816
13                       4528               12.0            0.265018
14                       2022                2.0            0.098912
15                       3639               16.0            0.439681
16                       2975               12.0            0.403361
17                       3385               12.0            0.354505
18                       1976                7.0            0.354251
19                       3506                0.0            0.000000
20                       4291                4.0            0.093218
21                       3537                3.0            0.084818
22                       5894               16.0            0.271463
23                       4165               33.0            0.792317
24                       4592               12.0            0.261324
25                       2314                7.0            0.302506
26                       2523                4.0            0.158541
27                       1089               12.0            1.101928
28                       1653                1.0            0.060496
29                       4275                9.0            0.210526
30                       2483                8.0            0.322191
31                       2816               41.0            1.455966
32                       4525               12.0            0.265193
33                       3151                3.0            0.095208
34                       2486               50.0            2.011263
35                       5507               21.0            0.381333
36                       6393              117.0            1.830127
37                       3306               62.0            1.875378
38                       2891               17.0            0.588032
39                       2760               43.0            1.557971
40                       4481               23.0            0.513278
41                       5342               30.0            0.561587
42                       7140               15.0            0.210084
43                       5063              144.0            2.844164
44                       4975               23.0            0.462312
45                       5598               40.0            0.714541
46                       3519                7.0            0.198920
47                       5121               16.0            0.312439
48                       2954                0.0            0.000000
49                       2454                6.0            0.244499

In [9]:
# ============================================================
# MISSINGNESS VS TRANSACTION CLASS
# ============================================================

tx_classes = pd.read_csv(r"C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\txs_classes.csv")

print("Class dataset shape:", tx_classes.shape)

print("\nClass columns:")
print(tx_classes.columns.tolist())

print("\nFirst 5 rows:")
display(tx_classes.head())

Class dataset shape: (203769, 2)

Class columns:
['txId', 'class']

First 5 rows:

    txId  class
0   3321      3
1  11108      3
2  51816      3
3  68869      2
4  89273      2

In [10]:
# ============================================================
# MERGE CLASS INFORMATION
# ============================================================

# Merge class information with transaction features
tx_audit = tx_features[["txId", "Time step"] + augmented_cols].copy()

tx_audit = tx_audit.merge(
    tx_classes,
    on="txId",
    how="left"
)

print("Merged audit dataset shape:", tx_audit.shape)

print("\nColumns:")
print(tx_audit.columns.tolist())

Merged audit dataset shape: (203769, 20)

Columns:
['txId', 'Time step', 'in_txs_degree', 'out_txs_degree', 'total_BTC', 'fees', 'size', 'num_input_addresses', 'num_output_addresses', 'in_BTC_min', 'in_BTC_max', 'in_BTC_mean', 'in_BTC_median', 'in_BTC_total', 'out_BTC_min', 'out_BTC_max', 'out_BTC_mean', 'out_BTC_median', 'out_BTC_total', 'class']

In [11]:
# ============================================================
# COMPARE MISSING AUGMENTED FEATURES BY CLASS
# ============================================================

# A transaction is considered missing augmented data
# when all 17 augmented features are missing.

tx_audit["Augmented_Missing"] = (
    tx_audit[augmented_cols]
    .isna()
    .all(axis=1)
)

print("Missing augmented transactions:")
print(
    tx_audit["Augmented_Missing"]
    .value_counts()
)


# ------------------------------------------------------------
# Class distribution of missing transactions
# ------------------------------------------------------------

missing_by_class = pd.crosstab(
    tx_audit["class"],
    tx_audit["Augmented_Missing"]
)

print("\nClass vs augmented-feature missingness:")
display(missing_by_class)


# ------------------------------------------------------------
# Percentage missing within each class
# ------------------------------------------------------------

class_missing_pct = (
    tx_audit
    .groupby("class")["Augmented_Missing"]
    .agg(
        Total_Transactions="count",
        Missing_Augmented="sum"
    )
)

class_missing_pct["Missing_Percentage"] = (
    class_missing_pct["Missing_Augmented"]
    / class_missing_pct["Total_Transactions"]
    * 100
)

print("\nMissing percentage within each class:")

display(class_missing_pct)

Missing augmented transactions:
Augmented_Missing
False    202804
True        965
Name: count, dtype: int64

Class vs augmented-feature missingness:

Augmented_Missing   False  True
class
1                    4545      0
2                   41500    519
3                  156759    446

Missing percentage within each class:

       Total_Transactions  Missing_Augmented  Missing_Percentage
class
1                    4545                  0            0.000000
2                   42019                519            1.235156
3                  157205                446            0.283706

In [12]:
# ============================================================
# CHECK GRAPH COVERAGE OF MISSING AUGMENTED TRANSACTIONS
# ============================================================

# Load the three relationship files

tx_edges = pd.read_csv(r"C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\txs_edgelist.csv")
addr_tx_edges = pd.read_csv(r"C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\AddrTx_edgelist.csv")
tx_addr_edges = pd.read_csv(r"C:\Users\koush\OneDrive\Documents\Financial_Forensics\data\raw\eliptic++\TxAddr_edgelist.csv")

print("Transaction edges shape:", tx_edges.shape)
print("Address -> Transaction shape:", addr_tx_edges.shape)
print("Transaction -> Address shape:", tx_addr_edges.shape)

Transaction edges shape: (234355, 2)
Address -> Transaction shape: (477117, 2)
Transaction -> Address shape: (837124, 2)

In [13]:
# ============================================================
# IDENTIFY THE 965 MISSING TRANSACTIONS
# ============================================================

missing_tx_ids = set(
    tx_audit.loc[
        tx_audit["Augmented_Missing"],
        "txId"
    ]
)

print("Missing augmented transactions:",
      len(missing_tx_ids))

Missing augmented transactions: 965

In [14]:
# ============================================================
# CHECK TRANSACTION GRAPH COVERAGE
# ============================================================

tx_graph_ids = set(
    tx_edges["txId1"]
).union(
    set(tx_edges["txId2"])
)

missing_in_tx_graph = missing_tx_ids.intersection(
    tx_graph_ids
)

print(
    "Missing transactions present in transaction graph:",
    len(missing_in_tx_graph)
)

print(
    "Missing transactions NOT present in transaction graph:",
    len(missing_tx_ids - tx_graph_ids)
)

Missing transactions present in transaction graph: 965
Missing transactions NOT present in transaction graph: 0

In [15]:
# ============================================================
# CHECK INPUT ADDRESS COVERAGE
# ============================================================

input_tx_ids = set(
    addr_tx_edges["txId"]
)

missing_with_input_addresses = (
    missing_tx_ids.intersection(input_tx_ids)
)

print(
    "Missing transactions with input-address records:",
    len(missing_with_input_addresses)
)

print(
    "Missing transactions WITHOUT input-address records:",
    len(missing_tx_ids - input_tx_ids)
)


# ============================================================
# CHECK OUTPUT ADDRESS COVERAGE
# ============================================================

output_tx_ids = set(
    tx_addr_edges["txId"]
)

missing_with_output_addresses = (
    missing_tx_ids.intersection(output_tx_ids)
)

print(
    "Missing transactions with output-address records:",
    len(missing_with_output_addresses)
)

print(
    "Missing transactions WITHOUT output-address records:",
    len(missing_tx_ids - output_tx_ids)
)

Missing transactions with input-address records: 0
Missing transactions WITHOUT input-address records: 965
Missing transactions with output-address records: 0
Missing transactions WITHOUT output-address records: 965

In [16]:
# ============================================================
# COMPARE MISSING VS NON-MISSING AUGMENTED TRANSACTIONS
# ============================================================

tx_audit["Augmented_Missing"] = (
    tx_audit[augmented_cols]
    .isna()
    .all(axis=1)
)

# Basic comparison of the two groups
comparison = tx_audit.groupby(
    "Augmented_Missing"
)[["Time step"]].agg(
    ["count", "min", "max", "mean", "median"]
)

display(comparison)

                  Time step
                      count min max       mean median
Augmented_Missing
False                202804   1  49  23.807213   23.0
True                    965   1  49  31.566839   36.0

In [17]:
# ============================================================
# CLASS DISTRIBUTION: MISSING VS AVAILABLE
# ============================================================

class_comparison = pd.crosstab(
    tx_audit["Augmented_Missing"],
    tx_audit["class"],
    normalize="index"
) * 100

class_comparison.columns = [
    f"Class_{c}_Percentage"
    for c in class_comparison.columns
]

display(class_comparison)

                   Class_1_Percentage  Class_2_Percentage  Class_3_Percentage
Augmented_Missing
False                         2.24108           20.463107           77.295813
True                          0.00000           53.782383           46.217617

In [18]:
# ============================================================
# TRANSACTION-LEVEL COMPARISON
# MISSING vs AVAILABLE AUGMENTED FEATURES
# ============================================================

comparison_features = [
    "Time step",
    "Local_feature_1",   # Transaction volume
    "Local_feature_2",   # Fees
    "Local_feature_5",   # Number of inputs
    "Local_feature_6",   # Number of outputs
    "Local_feature_7",   # Unique input addresses
    "Local_feature_15"   # Near-constant feature
]

comparison_table = (
    tx_features
    .merge(
        tx_audit[["txId", "Augmented_Missing"]],
        on="txId",
        how="left"
    )
    .groupby("Augmented_Missing")[comparison_features]
    .agg(["mean", "median", "min", "max"])
)

display(comparison_table)

                   Time step                Local_feature_1            \
                        mean median min max            mean    median
Augmented_Missing
False              23.807213   23.0   1  49        0.000757 -0.169160
True               31.566839   36.0   1  49       -0.159009 -0.172479

                                       Local_feature_2            ...  \
                        min        max            mean    median  ...
Augmented_Missing                                                 ...
False             -0.172983  71.681966       -0.000199 -0.132897  ...
True              -0.172982   0.457773        0.041831 -0.066347  ...

                  Local_feature_6            Local_feature_7            \
                              min        max            mean    median
Augmented_Missing
False                   -0.113002  54.565178        0.000254 -0.061584
True                    -0.113002   0.893345       -0.053385 -0.061584

                                        Local_feature_15                      \
                        min         max             mean    median       min
Augmented_Missing
False             -0.061584  113.440873        -0.000779 -0.013282 -0.013282
True              -0.061584    0.547008         0.163662 -0.013282 -0.013282


                          max
Augmented_Missing
False              119.477578
True                 1.718470

[2 rows x 28 columns]

In [19]:
# ============================================================
# FEATURE DISTRIBUTION AND SCALE AUDIT
# ============================================================

feature_stats = tx_features[feature_cols].describe().T

feature_stats["skewness"] = tx_features[feature_cols].skew()
feature_stats["missing_count"] = tx_features[feature_cols].isna().sum()
feature_stats["unique_count"] = tx_features[feature_cols].nunique()

display(
    feature_stats[
        [
            "count",
            "mean",
            "std",
            "min",
            "25%",
            "50%",
            "75%",
            "max",
            "skewness",
            "missing_count",
            "unique_count"
        ]
    ]
)

,count,mean,std,min,25%,50%,75%,max,skewness,missing_count,unique_count
Time step,203769.0,2.384396e+01,15.172170,1.000000,9.000000,23.000000,38.000000,49.000000,0.044608,0,49
Local_feature_1,203769.0,2.231681e-17,1.000002,-0.172983,-0.172532,-0.169204,-0.131855,71.681966,26.781532,0,195328
Local_feature_2,203769.0,1.785345e-17,1.000002,-0.210553,-0.180327,-0.132897,-0.055242,73.595052,21.477146,0,28906
Local_feature_3,203769.0,3.570689e-17,1.000002,-1.756361,-1.201369,0.463609,1.018602,2.683580,-0.064169,0,9
Local_feature_4,203769.0,6.792678e-17,1.000002,-0.121970,-0.121970,-0.121970,-0.121970,49.027598,24.874113,0,300
...,...,...,...,...,...,...,...,...,...,...,...
out_BTC_min,202804.0,6.308157e-01,10.991307,0.000000,0.002700,0.015000,0.100195,2010.466695,86.771545,965,134954
out_BTC_max,202804.0,2.650834e+01,154.563163,0.000006,0.059000,0.500000,5.726287,11311.828314,26.411570,965,174059
out_BTC_mean,202804.0,1.185257e+01,67.111277,0.000006,0.035485,0.280447,2.618991,2998.404230,22.488845,965,195550
out_BTC_median,202804.0,1.136366e+01,65.905428,0.000005,0.026874,0.215289,2.157049,2998.404230,22.971070,965,190593
out_BTC_total,202804.0,2.754456e+01,158.906034,0.000006,0.072398,0.606105,6.590898,11391.855937,26.721203,965,195231

In [20]:
# ============================================================
# MOST SKEWED FEATURES
# ============================================================

skewed_features = (
    feature_stats[["skewness", "unique_count", "missing_count"]]
    .sort_values("skewness", key=lambda x: x.abs(), ascending=False)
)

display(skewed_features.head(20))

                        skewness  unique_count  missing_count
Local_feature_34      235.935705          4871              0
Local_feature_37      222.670091          8521              0
Local_feature_35      200.435594          6808              0
Local_feature_36      148.300704          3905              0
Local_feature_73      129.564567         23759              0
Local_feature_14      129.067301           275              0
Local_feature_72      127.480130         23174              0
Local_feature_5       122.457259           271              0
num_output_addresses  122.169977           271            965
Local_feature_71      110.789891         17646              0
Aggregate_feature_37  110.015392        156738              0
Aggregate_feature_68  109.982219           302              0
Aggregate_feature_69  103.895507          8013              0
out_txs_degree        102.133669            63            965
Aggregate_feature_67   97.170905            90              0
Local_feature_15       96.338745            51              0
Local_feature_70       91.430608          2150              0
Local_feature_16       86.930341        135361              0
out_BTC_min            86.771545        134954            965
Local_feature_10       71.875922         47979              0

In [21]:
# ============================================================
# LOW-CARDINALITY FEATURES
# ============================================================

low_cardinality = (
    feature_stats[["unique_count", "mean", "std", "skewness"]]
    .sort_values("unique_count")
)

display(low_cardinality.head(20))

                      unique_count          mean        std    skewness
Local_feature_3                  9  3.570689e-17   1.000002   -0.064169
Aggregate_feature_19             9 -7.141378e-17   1.000002    0.114967
Aggregate_feature_20             9 -1.071207e-16   1.000002   -0.112249
Aggregate_feature_55             9 -2.142414e-16   1.000002    0.360434
Aggregate_feature_56             9 -1.071207e-16   1.000002   -0.769587
Time step                       49  2.384396e+01  15.172170    0.044608
Local_feature_15                51  8.815139e-17   1.000002   96.338745
out_txs_degree                  63  1.152837e+00   1.898455  102.133669
Aggregate_feature_67            90 -4.686530e-17   1.000002   97.170905
Local_feature_7                108  2.678017e-17   1.000002   55.042965
in_txs_degree                  145  1.152551e+00   3.920123   25.171984
Aggregate_feature_25           199  5.802370e-17   1.000002   27.588812
num_output_addresses           271  4.216746e+00  50.497139  122.169977
Local_feature_5                271  7.531922e-17   1.000002  122.457259
Local_feature_14               275  4.770218e-17   1.000002  129.067301
Local_feature_4                300  6.792678e-17   1.000002   24.874113
Local_feature_6                300  6.081330e-17   1.000002   27.156023
num_input_addresses            300  2.631748e+00  13.357720   24.817338
Aggregate_feature_68           302  0.000000e+00   1.000002  109.982219
Aggregate_feature_26           311 -1.115840e-17   1.000002   17.481876

In [22]:
# ============================================================
# EXTREME VALUE / TAIL ANALYSIS
# ============================================================

percentiles = [0, 1, 5, 25, 50, 75, 95, 99, 99.9, 100]

tail_stats = tx_features[feature_cols].quantile(
    [p / 100 for p in percentiles]
).T

tail_stats.columns = [
    "min",
    "p1",
    "p5",
    "p25",
    "p50",
    "p75",
    "p95",
    "p99",
    "p99_9",
    "max"
]

display(tail_stats)

,min,p1,p5,p25,p50,p75,p95,p99,p99_9,max
Time step,1.000000,1.000000,2.000000,9.000000,23.000000,38.000000,47.000000,49.000000,49.000000,49.000000
Local_feature_1,-0.172983,-0.172976,-0.172929,-0.172532,-0.169204,-0.131855,0.647112,2.575570,9.810823,71.681966
Local_feature_2,-0.210553,-0.197375,-0.188840,-0.180327,-0.132897,-0.055242,0.246729,2.360693,14.688601,73.595052
Local_feature_3,-1.756361,-1.201369,-1.201369,-1.201369,0.463609,1.018602,1.573595,1.573595,2.128587,2.683580
Local_feature_4,-0.121970,-0.121970,-0.121970,-0.121970,-0.121970,-0.121970,0.253218,1.753968,14.810495,49.027598
...,...,...,...,...,...,...,...,...,...,...
out_BTC_min,0.000000,0.000037,0.000200,0.002700,0.015000,0.100195,1.184933,9.485818,86.046996,2010.466695
out_BTC_max,0.000006,0.001000,0.007108,0.059000,0.500000,5.726287,125.007976,428.795483,1531.144207,11311.828314
out_BTC_mean,0.000006,0.000633,0.003975,0.035485,0.280447,2.618991,55.319283,203.609470,688.063120,2998.404230
out_BTC_median,0.000005,0.000300,0.002418,0.026874,0.215289,2.157049,52.730422,200.414351,617.237357,2998.404230
out_BTC_total,0.000006,0.001100,0.008661,0.072398,0.606105,6.590898,130.759500,437.093689,1587.095515,11391.855937

In [23]:
# ============================================================
# WORST SKEWED FEATURES — DETAILED DISTRIBUTION
# ============================================================

worst_features = [
    "Local_feature_34",
    "Local_feature_37",
    "Local_feature_35",
    "Local_feature_36",
    "Local_feature_73",
    "Local_feature_14",
    "Local_feature_5",
    "num_output_addresses",
    "out_txs_degree",
    "out_BTC_min"
]

display(
    tail_stats.loc[worst_features]
)

,min,p1,p5,p25,p50,p75,p95,p99,p99_9,max
Local_feature_34,-0.024669,-0.024669,-0.024669,-0.024669,-0.024669,-0.024669,-0.024656,-0.003760,8.621031,287.891515
Local_feature_37,-0.026215,-0.026215,-0.026215,-0.026215,-0.026215,-0.026215,-0.026177,0.011551,8.399564,280.566222
Local_feature_35,-0.031272,-0.031272,-0.031272,-0.031272,-0.031272,-0.031272,-0.031230,0.007913,8.068397,269.701184
Local_feature_36,-0.023045,-0.023045,-0.023045,-0.023045,-0.023045,-0.023045,-0.023045,-0.012675,4.748401,289.204388
Local_feature_73,-0.015071,-0.015071,-0.015071,-0.015071,-0.015071,-0.015071,-0.014898,0.023671,1.115057,151.035179
Local_feature_14,-0.063200,-0.063200,-0.063200,-0.042955,-0.042955,-0.042955,0.078513,0.463161,6.010196,265.263236
Local_feature_5,-0.063725,-0.063725,-0.063725,-0.043875,-0.043875,-0.043875,0.075226,0.452376,7.754327,260.090707
num_output_addresses,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,8.000000,27.000000,410.850000,13107.000000
out_txs_degree,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2.000000,5.000000,16.000000,472.000000
out_BTC_min,0.000000,0.000037,0.000200,0.002700,0.015000,0.100195,1.184933,9.485818,86.046996,2010.466695

In [24]:
# ============================================================
# ZERO / NEAR-ZERO VALUE AUDIT
# ============================================================

zero_stats = pd.DataFrame(index=feature_cols)

zero_stats["zero_count"] = [
    (tx_features[col] == 0).sum()
    for col in feature_cols
]

zero_stats["zero_percentage"] = (
    zero_stats["zero_count"] / len(tx_features) * 100
)

zero_stats["near_zero_percentage"] = [
    (tx_features[col].abs() < 1e-6).sum() / len(tx_features) * 100
    for col in feature_cols
]

display(
    zero_stats
    .sort_values("zero_percentage", ascending=False)
    .head(25)
)

                  zero_count  zero_percentage  near_zero_percentage
in_txs_degree          54970        26.976625             26.976625
out_txs_degree         36989        18.152418             18.152418
out_BTC_min              181         0.088826              0.089317
fees                      67         0.032880              0.032880
Time step                  0         0.000000              0.000000
Local_feature_1            0         0.000000              0.000000
Local_feature_2            0         0.000000              0.000000
Local_feature_7            0         0.000000              0.000000
Local_feature_8            0         0.000000              0.000000
Local_feature_9            0         0.000000              0.000000
Local_feature_10           0         0.000000              0.000000
Local_feature_11           0         0.000000              0.000000
Local_feature_12           0         0.000000              0.000000
Local_feature_13           0         0.000000              0.000000
Local_feature_14           0         0.000000              0.000000
Local_feature_15           0         0.000000              0.000000
Local_feature_16           0         0.000000              0.000491
Local_feature_17           0         0.000000              0.000000
Local_feature_18           0         0.000000              0.000000
Local_feature_3            0         0.000000              0.000000
Local_feature_4            0         0.000000              0.000000
Local_feature_5            0         0.000000              0.000000
Local_feature_6            0         0.000000              0.000000
Local_feature_23           0         0.000000              0.000000
Local_feature_24           0         0.000000              0.000000

In [25]:
# ============================================================
# LOCAL_FEATURE_15 VALUE DISTRIBUTION
# ============================================================

lf15_distribution = (
    tx_features["Local_feature_15"]
    .value_counts(dropna=False)
    .sort_index()
    .to_frame("count")
)

lf15_distribution["percentage"] = (
    lf15_distribution["count"] / len(tx_features) * 100
)

display(lf15_distribution)

                   count  percentage
Local_feature_15
-0.013282         203463   99.849830
 0.159894             84    0.041223
 0.333069              9    0.004417
 0.506244              5    0.002454
 0.679419             19    0.009324
 0.852594              6    0.002945
 1.198944              1    0.000491
 1.372120              5    0.002454
 1.545295              1    0.000491
 1.718470            133    0.065270
 2.930696              1    0.000491
 3.450222              1    0.000491
 3.796572              1    0.000491
 7.086900              1    0.000491
 12.282155             1    0.000491
 13.148030             1    0.000491
 14.360257             1    0.000491
 15.052957             1    0.000491
 15.745658             1    0.000491
 17.131059             1    0.000491
 17.304234             1    0.000491
 21.287263             1    0.000491
 27.175218             1    0.000491
 27.867919             1    0.000491
 30.465546             1    0.000491
 36.526677             1    0.000491
 37.738903             1    0.000491
 38.951129             1    0.000491
 39.643830             2    0.000982
 41.202406             1    0.000491
 42.760983             1    0.000491
 42.934158             1    0.000491
 45.012260             1    0.000491
 46.917186             1    0.000491
 54.536893             1    0.000491
 76.010613             1    0.000491
 83.803495             1    0.000491
 88.132874             1    0.000491
 94.886705             1    0.000491
 97.137982             1    0.000491
 98.350209             1    0.000491
 100.081960            1    0.000491
 100.601486            1    0.000491
 100.947836            1    0.000491
 102.333237            1    0.000491
 105.623565            1    0.000491
 109.606594            1    0.000491
 112.550572            2    0.000982
 113.935973            1    0.000491
 116.187250            1    0.000491
 119.477578            1    0.000491

In [26]:
# ============================================================
# LOW-CARDINALITY FEATURE VALUE COUNTS
# ============================================================

low_cardinality_features = [
    "Local_feature_3",
    "Aggregate_feature_19",
    "Aggregate_feature_20",
    "Aggregate_feature_55",
    "Aggregate_feature_56"
]

for col in low_cardinality_features:
    print(f"\n{'='*60}")
    print(f"{col}")
    print(f"{'='*60}")

    print(
        tx_features[col]
        .value_counts()
        .sort_index()
    )

============================================================
Local_feature_3
============================================================
Local_feature_3
-1.756361       67
-1.201369    72814
-0.646376     5569
-0.091383    17150
 0.463609    45528
 1.018602    49916
 1.573595    11323
 2.128587     1389
 2.683580       13
Name: count, dtype: int64

============================================================
Aggregate_feature_19
============================================================
Aggregate_feature_19
-1.626385     2455
-1.096336    76627
-0.566287     6155
-0.036238    18032
 0.493811    40925
 1.023860    43463
 1.553909    11626
 2.083958     4454
 2.614007       32
Name: count, dtype: int64

============================================================
Aggregate_feature_20
============================================================
Aggregate_feature_20
-1.781034      976
-1.267340    64283
-0.753646     5241
-0.239953    15002
 0.273741    39771
 0.787435    51236
 1.301128    19457
 1.814822     7711
 2.328516       92
Name: count, dtype: int64

============================================================
Aggregate_feature_55
============================================================
Aggregate_feature_55
-1.511910     2694
-0.968903    87650
-0.425896     9632
 0.117111    18135
 0.660117    38744
 1.203124    33886
 1.746131     9696
 2.289138     3197
 2.832144      135
Name: count, dtype: int64

============================================================
Aggregate_feature_56
============================================================
Aggregate_feature_56
-2.466561      204
-1.943850    28514
-1.421138     6040
-0.898426     6587
-0.375715    26700
 0.146997    56464
 0.669709    44949
 1.192421    32116
 1.715132     2195
Name: count, dtype: int64

In [27]:
# ============================================================
# CELL 10 — FEATURE GROUP MAPPING
# ============================================================

# Define the feature groups based on the Elliptic++ structure

local_features = [f"Local_feature_{i}" for i in range(1, 94)]

aggregate_features = [f"Aggregate_feature_{i}" for i in range(1, 73)]

augmented_features = [
    "in_txs_degree",
    "out_txs_degree",
    "total_BTC",
    "fees",
    "size",
    "num_input_addresses",
    "num_output_addresses",
    "in_BTC_min",
    "in_BTC_max",
    "in_BTC_mean",
    "in_BTC_median",
    "in_BTC_total",
    "out_BTC_min",
    "out_BTC_max",
    "out_BTC_mean",
    "out_BTC_median",
    "out_BTC_total"
]

# Create mapping table
feature_groups = pd.DataFrame({
    "feature": (
        ["Time step"] +
        local_features +
        aggregate_features +
        augmented_features
    )
})

# Assign group
feature_groups["group"] = (
    ["Time step"] +
    ["Local"] * len(local_features) +
    ["Aggregate"] * len(aggregate_features) +
    ["Elliptic++ augmented"] * len(augmented_features)
)

# Original feature number
feature_groups["feature_number"] = range(1, 184)

# Reorder columns
feature_groups = feature_groups[
    ["feature_number", "feature", "group"]
]

display(feature_groups.head(10))

print("\nLast 20 features:")
display(feature_groups.tail(20))

print("\nFeature group counts:")
print(feature_groups["group"].value_counts())

   feature_number          feature      group
0               1        Time step  Time step
1               2  Local_feature_1      Local
2               3  Local_feature_2      Local
3               4  Local_feature_3      Local
4               5  Local_feature_4      Local
5               6  Local_feature_5      Local
6               7  Local_feature_6      Local
7               8  Local_feature_7      Local
8               9  Local_feature_8      Local
9              10  Local_feature_9      Local

Last 20 features:

     feature_number               feature                 group
163             164  Aggregate_feature_70             Aggregate
164             165  Aggregate_feature_71             Aggregate
165             166  Aggregate_feature_72             Aggregate
166             167         in_txs_degree  Elliptic++ augmented
167             168        out_txs_degree  Elliptic++ augmented
168             169             total_BTC  Elliptic++ augmented
169             170                  fees  Elliptic++ augmented
170             171                  size  Elliptic++ augmented
171             172   num_input_addresses  Elliptic++ augmented
172             173  num_output_addresses  Elliptic++ augmented
173             174            in_BTC_min  Elliptic++ augmented
174             175            in_BTC_max  Elliptic++ augmented
175             176           in_BTC_mean  Elliptic++ augmented
176             177         in_BTC_median  Elliptic++ augmented
177             178          in_BTC_total  Elliptic++ augmented
178             179           out_BTC_min  Elliptic++ augmented
179             180           out_BTC_max  Elliptic++ augmented
180             181          out_BTC_mean  Elliptic++ augmented
181             182        out_BTC_median  Elliptic++ augmented
182             183         out_BTC_total  Elliptic++ augmented

Feature group counts:
group
Local                   93
Aggregate               72
Elliptic++ augmented    17
Time step                1
Name: count, dtype: int64

In [28]:
# ============================================================
# CELL 11 — VERIFY FEATURE GROUP MAPPING
# ============================================================

actual_features = set(feature_cols)
mapped_features = set(feature_groups["feature"])

missing_from_mapping = actual_features - mapped_features
extra_in_mapping = mapped_features - actual_features

print("Actual feature count :", len(actual_features))
print("Mapped feature count :", len(mapped_features))

print("\nFeatures missing from mapping:")
print(missing_from_mapping)

print("\nFeatures present in mapping but not dataset:")
print(extra_in_mapping)

if not missing_from_mapping and not extra_in_mapping:
    print("\n✅ Feature mapping perfectly matches the dataset.")
else:
    print("\n⚠️ Mapping needs investigation.")

Actual feature count : 183
Mapped feature count : 183

Features missing from mapping:
set()

Features present in mapping but not dataset:
set()

✅ Feature mapping perfectly matches the dataset.